### ISSUE TITLE
Next alarm/timer should be device_class timestamp

### ISSUE THREAD

**Issue by gary-reyes** [leikoilja/ha-google-home#105]
I would like to use some blueprints that use timestamps but was surprised to find that I could not use the next alarm or or timers  sensor because they are not device_class timestamp. Since these sensor provide a timestamp, they should have this device class

**Comment by leikoilja** [comment]
Hmm... clearly we have missed something. @gary-reyes, can you please elaborate a bit more what do you mean by device class. Perhaps some HA documentation or examples you could find? :)

**Comment by gary-reyes** [comment]
https://www.home-assistant.io/integrations/sensor/
https://developers.home-assistant.io/docs/core/entity/sensor/

I wanted to use this blueprint:
https://community.home-assistant.io/t/wake-up-light-alarm-with-sunrise-effect/255193

It filters out sensors that are device_class timestamp.

**Comment by DurgNomis-drol** [comment]
@leikoilja We should change it so it matches the same class as the mobile app. It is device_class `timestamp`. It was the intention that it should just mimic it 😄 I just never actually checked it, that is my fault.
