### ISSUE TITLE
Filter chromecast devices

### ISSUE THREAD

**Issue by gary-reyes** [leikoilja/ha-google-home#118]
Since the integration provides alarms and timers, chromecast should be filtered from list ofdiscovered devices since they do not support either of the two features.

**Comment by leikoilja** [comment]
Hey, @gary-reyes. 
Well, the integration already filters devices that do not support alarms and filters by trying to make an API call to fetch those and if it doesn't succeed it filters those devices. What issue do you have? Are your chromecast devices displayed anywhere?

**Comment by gary-reyes** [comment]
I have chromecast with google TV. If you try setting an alarm or timer using the controller, the assistant will say they aren't supported.

**Comment by KapJI** [comment]
What controller? For chromecast devices we only expose `_device` sensor which contains auth token. This is intentional for people who want to use this token to access other API endpoints e.g. reboot.

**Comment by gary-reyes** [comment]
I apologize. I should have looked at it more closely. You are correct. The chromecast with google TV do have the behavior you indicated. The tv i was looking at was a tv with "chromecast built-in". This does show the issue i indicated.

See image below.


On a separate topic, not to deter from original issue, I don't see why the device sensor is included. I know you guys' rationale but I do not see the vast majority of users using it. The use case also doesn't make sense. I am assuming that this is static data or a token that might refresh every so often. I don't see how an automation could be created from this . It seems that the intention is that someone will then use this to manually run some script or code elsewhere outside of HA? To me that just seems disconnected.  If you guys know other endpoints this could be used for, why not expose as a service? Something like google_home.reboot? Why leave it to a power user to implement?

I think this integration has a good chance of becoming part of core HA and could be extremely useful but the token sensor will not help since it seems like exposing the token is a security issue. Just my 2 cents. Not looking to start a new discussion. I want to keep discussion on topic.

![Screenshot_20210327-073101](https://user-images.githubusercontent.com/36871757/112720781-8f172d00-8ece-11eb-8b09-bf7c1d583dab.png)

**Comment by KapJI** [comment]
If you mean "Invalid timestamp" issue that it's tracked by #114. Basically it's a frontend issue, data is there.

> but I do not see the vast majority of users using it

Well, this is unproven statement, I see some value for having it.

> I don't see how an automation could be created from this.

You can define automation of custom service which will use this token to perform the request to the local API.

> why not expose as a service

This API may change over time and be different for different devices. It's hard to cover all endpoints and we don't aim to do that. But we allow power users easy access to this token in order to do that if they want to.

You're welcome to send the PR 🙂

> I think this integration has a good chance of becoming part of core HA

I don't think we want this. Having it in core makes maintaining much more difficult, here we can control releases and testing, in core we can't. It can be easily installed from HACS, this should be enough. 

I personally think Home Assistant needs to move most of the components from the core to something like HACS. Because right now it's too huge and it's very painful to maintain such many components. But this is up to them.

**Comment by gary-reyes** [comment]
No i don't meant the invalid timestamp. The issue here is there this device "chromecast built-in" does not support alarms or timers.
![Screenshot_20210327-081323](https://user-images.githubusercontent.com/36871757/112721886-57ab7f00-8ed4-11eb-909f-35301b1bc54c.png)

**Comment by KapJI** [comment]
That's interesting. I also have Android TV device (Nvidia Shield) but token disappears after the first update and alarm sensor was never added.

So it seems your device actually responds on alarms endpoint with empty list although it's not possible to set any alarms there. Not sure how to avoid adding sensors in this case I really don't think we should have a hardcoded list of supported devices. Let's keep as is for now before we find a better solution.

**Comment by leikoilja** [comment]
Do you guys think we should provide some sort of `config_flow` option for whitelist/blacklist devices based on their IPs? It can be an optional setting for "power users" where one could for example add static IP of their TV to be blacklisted? It would it be hectic to do so?

**Comment by gary-reyes** [comment]
There is already a way to disable devices altogether from within HA. This is what I would use if there wasn't an automatic way filter these device

**Comment by KapJI** [comment]
There is a standard mechanism in HA to hide entities (in customization). These queries should be harmless so I don't think we need these in config flow.

**Comment by leikoilja** [comment]
Sounds good! Sorry, @gary-reyes, seems like we can't do much at his point to introduce the filtering of the TV device you have. It seems a very edge-case when TV is returning lists of alarms/devices where these features are actually not supported. 
I'll close this issue in a meantime
