### ISSUE TITLE
Retry alarms/timers fetching from every discovered device on every coordinator update

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#119]
## Describe the bug
Google Home devices are mistakenly filtered:
Devices that actually contain alarms/timers are filtered out if the API request fails to establish because of underlying issues of `pychromcast`.
Please see there two log entries where my Google Home devices were filtered out because the API request to them unexpectedly returned `404`.

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
Google Home v1.0.1
```

## Logs
<img width="1066" alt="Screenshot 2021-03-27 at 08 32 23" src="https://user-images.githubusercontent.com/10655107/112713966-511f0680-8ed8-11eb-8cc2-8a3ffa915c47.png">
<img width="1072" alt="Screenshot 2021-03-27 at 08 33 33" src="https://user-images.githubusercontent.com/10655107/112713970-53816080-8ed8-11eb-8647-483ca7ba2f6e.png">

From these logs, you see that I used to have a working `Kitchen` device that got filtered out and no more data fetched from it (1st screenshot) and `Living Room` device that also got filtered out (2nd screenshot)

## Expected behaviour
Retry fetching alarms/timers from device(s) on every coordinator update

**Comment by KapJI** [comment]
We should probably retry on every coordinator update. If API returns new devices or if old ones start to return alarms, they should be added.

**Comment by leikoilja** [comment]
I agree that we should instead retry fetching alarms/timers from device(s) on every coordinator update (currently every 10ish sec), however, what do you mean by querying Foyer API on the interval? As you say, right now we do a call during the initial setup and then, if I'm not mistaken, every time the access token is expired (~24h). Do you think there is any benefit of doing it more often?

**Comment by KapJI** [comment]
Yeah, if we query it every few minutes, then new added devices should become quickly available.

**Comment by leikoilja** [comment]
Hmmm we could do so... Maybe it will cover some edge cases when someone configures a new device and expects to see that in HA `Google Home` integration. New tickets like:
- retry fetching alarms/timers from device(s) on every coordinator update?
- fetching Foyer devices every 10 mins?

**Comment by KapJI** [comment]
Sounds good.

**Comment by leikoilja** [comment]
1. Let's keep this issue (#119) as a tracking issue for retrying fetching alarms/timers on every coordinator update
2. Periodically fetching Foyer devices tracking issue - #122
