### ISSUE TITLE
Remove table of contents from README

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#120]
Github now has autogenerated table of contents:
<img width="329" alt="Screenshot 2021-03-27 at 11 16 58" src="https://user-images.githubusercontent.com/3767331/112719000-5ab36900-8eee-11eb-87f7-6c2339bdcc9c.png">

Should we remove manual one to avoid maintaining it? Or it's nicer to have both?

**Comment by leikoilja** [comment]
Uuuu, github steps up their game 😄  I'm neutral. I guess we can keep it for now, doesn't seem to take much of effort to maintain it at this points and looks pretty good :)

**Comment by KapJI** [comment]
Alright, let's keep it. I actually just noticed it, it's not obvious it's there.
