### ISSUE TITLE
Update glocaltokens to v0.3

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#160]
@DurgNomis-drol, @KapJI as promised here is a new version of `glocaltokens`
See https://github.com/leikoilja/glocaltokens/releases/tag/v0.3.0 (See the breaking changes)

Before we upgrade `glocaltokens` we need to make sure it's not going to break the integration.

**Comment by KapJI** [comment]
In `api.py` `device.ip` should be changed to `device.ip_address`. Other than that it should be fine.

@DurgNomis-drol can you check that `remove_service` error is resolved with `0.3.0`?
