### ISSUE TITLE
Support for family notes

### ISSUE THREAD

**Issue by apaperclip** [leikoilja/ha-google-home#169]
**Is your feature request related to a problem? Please describe.**

I would like to present visual notes/reminders on a google home hub/nest hub display.  

**Describe the solution you'd like**

Google family notes may provide a way to do this https://support.google.com/assistant/answer/10243081?hl=en 
CRUD operations for these notes from HA would be convenient and powerful.  

**Describe alternatives you've considered**

Today we use audible reminders or notifications to phone, but when its late at night being able to glance over and see the state is very quick and silent. 
The HA castable interface could be another option we use the hub as a picture frame by default, and family notes display over top.

**Additional context**

This will allow me to do things like pop up a family note at a certain time if the garage door is still open.  This IS a visual, persistent reminder of the condition (garage door open) and the HA can remove it when the condition clears.

**Comment by KapJI** [comment]
I don't think there is a way to do this with GH local API. Can you create them in the app?

**Comment by DurgNomis-drol** [comment]
Only endpoints [here](https://rithvikvibhu.github.io/GHLocalApi/) is possible as far as i know. 😄 But i like idea, maybe it will be possible in the future.

**Comment by KapJI** [comment]
Yeah, it seems they can be only created on Nest Hub itself, not even with Assistant on the phone.
Basically it's impossible to create them programatically.

**Comment by apaperclip** [comment]
Thanks for the fast replies!
