### ISSUE TITLE
Sleep sensing with Nest Hub (2nd gen)

### ISSUE THREAD

**Issue by 24jonny** [leikoilja/ha-google-home#194]
The second generation of the Nest Hub, released in 2021, supports a feature called [sleep sensing](https://support.google.com/googlenest/answer/10357290).
The Hub is using Google's low power radar sensor called Soli to determine if someone is close to it and if it is placed next to your bedside it will track your sleep and tell you at what time you lied down in bed, what time you started sleeping, what time you woke up and what time you finally got out of bed.

I would love to have access to precisely this information in Homeassistant. 
I'm thinking lying down in bed and the lights turn off or your pets won't trigger the motion sensors to turn on the night-light while you're in bed, you name it 😄  .

From what I understand you awesome people mimic the Google Home app and that is how you get the info about the timers.
Unfortunately the described insights show up in the Google Fit app but not the Home app (screenshot from Fit app below).
I'm curious if this information is accessible from the Home app for you as well.

Thanks for taking the time.

![GoogleFitApp_screenshot](https://user-images.githubusercontent.com/44023533/114518347-8e58f780-9c3f-11eb-993d-e649557d3788.png)

**Comment by KapJI** [comment]
We don't mimic Google Home app, we use Google Home local API: https://rithvikvibhu.github.io/GHLocalApi/#section/Google-Home-Local-API

If someone can figure out how Google Fit gets this data, we can probably add it.

**Comment by 24jonny** [comment]
Oh, okay, sorry for my uneducated and wrong description 😄

**Comment by leikoilja** [comment]
I can proxy google fit app to see what API calls it does to begin with, but i don't have google nest hub 2 to try it on, dont think that data will be there for me

**Comment by KapJI** [comment]
I'd expect device sends this data to Google and then app fetches this via grpc. Similar to home graph. Not that simple to reverse engineer, you'll probably need to bypass certificate pinning and extract proto file from the app.

**Comment by leikoilja** [comment]
haha sounds hectic :D i did something similar to proxy and see rest api calls on other apps, but not google home that uses grpc and other communication concepts. Might be a big challenge thou 🤔

**Comment by dshokouhi** [comment]
Google fit has a custom component that i am sure can get the data, the OAUTH permissions required will not be approved Google.  We looked into adding it in teh companion app but the permissions were all listed as restricted and only available to users on their own.  They have even more restrictions in the next week on google fit too :(

https://github.com/cyberjunky/home-assistant-google_fit

The companion app for android does actually support the new Sleep API that google released before announcing this feature on the nest hub 2 that might be of interest to some: 

https://developers.google.com/location-context/sleep

**Comment by DurgNomis-drol** [comment]
@dshokouhi Thanks for giving some insight.

This seems to be a part of Google Fit or am misunderstanding something? I think that Google Fit is out of scope for this integration, and should be either a part of a Google Fit integration or the companion app if it becomes possible in the future. 😄

**Comment by DurgNomis-drol** [comment]
Closing this unless more information about about how to implement it comes to light or if something else about it changes.

Feel free to reopen if you have other questions/more information regarding the subject. 😃
