### ISSUE TITLE
Reduce log warnings for offline and not-google-home devices

### ISSUE THREAD

**Issue by Duncank** [leikoilja/ha-google-home#195]
**Is your feature request related to a problem? Please describe.**
My logs in HA show these warnings: `Failed to connect to Soundbar device. The device is probably offline.` for a couple of my devices. Some of these devices are speakers with Google Cast built in, but not Google Home devices. I've got 6836 occurrences in the log since yesterday-morning. (since starting this issue, I've got 50 extra occurrences already)

**Describe the solution you'd like**
My soundbar isn't suddenly going to accept alarms and times; maybe these devices can be filtered and not tried every time / at all? Otherwise I would not expect to see a warning for this device, since it is default behaviour and I would not expect anything different from it.

**Additional context**
```
Logger: custom_components.google_home
Source: custom_components/google_home/api.py:428
Integration: Google Home (documentation, issues)
First occurred: 12 april 2021 8:57:41 (6836 occurrences)
Last logged: 11:26:37

Failed to connect to Soundbar device. The device is probably offline.
Failed to connect to Badkamer device. The device is probably offline.
```

**Comment by KapJI** [comment]
Yeah, this happens because of new Do No Disturb switch. We should print this messages to debug.

**Comment by sebirdman** [comment]
When I receive this message, it seems to happen at a very specific time for me on my google home devices every single day. I've seen it happen twice now at the exact same time frame. 

It just occurred about 10 minutes ago. I've got some alarms set, but they do not show up anymore after this happens.
