### ISSUE TITLE
Feature - Change unique id from device_name to something really unique.

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-google-home#199]
We can either use [this](https://rithvikvibhu.github.io/GHLocalApi/#operation/EurekaInfo) endpoint or as @leikoilja mentioned, we can generate one in glocaltokens.

What do you guys think is the best option?

**Original:**
Right now we use `device_name` in entity unique id. I think glocaltokens can provide some real device specific id for the device. Then HA should handle renames itself.

_Originally posted by @KapJI in https://github.com/leikoilja/ha-google-home/issues/184#issuecomment-818705358_

**Comment by KapJI** [comment]
The best option is some id from eurika or zeroconf. MAC address should be good as well.

**Comment by DurgNomis-drol** [comment]
I think it would be great if we can generate one from homegraph. It will also make it possible for us to then introduce a ``device.compatible` attribute, so the first time we actually know if the device is compatible, we don't need to check again. 😃

**Comment by leikoilja** [comment]
That does sound nice. Let's create a follow-up ticket on `glocaltokens` to getting an ID and passing it over

**Comment by gary-reyes** [comment]
Is there an ETA on this?

**Comment by KapJI** [comment]
I don't think anyone is working on this at the moment.

**Comment by leikoilja** [comment]
I'm currently traveling, but will be back home end of the week and can take a look at it, it sounds like a relatively quick fix. @gary-reyes, if interested - PRs are welcomed 💥

**Comment by skank01** [comment]
I'm seeing an error in my home assistant  logbook
Platform google_home does not generate unique IDs. ID Slaapkamer Parents/device already exists - ignoring sensor.slaapkamer_parents_device

Will this get fixed with it, or is my issue a total different one?

**Comment by leikoilja** [comment]
Gents, please kindly upgrade to 1.7.0 
https://github.com/leikoilja/ha-google-home/releases/tag/v1.7.0
Note, there are some breaking changes in the release notes :)
