### ISSUE TITLE
Display Home devices keep old alarms thus "next alarm" is always the same old alarm in the sensor state

### ISSUE THREAD

**Issue by andrec54** [leikoilja/ha-google-home#204]
## Describe the bug
The Google home devices with screen at least save all old alarms even after dismissed. Because of this the first alarm in the sensor state is the first one I ever set and can be weeks/months old and of no interest. It is only future alarms that are of interest in most usecases. The sensor should show the next upcoming alarm instead.

## Version of the integration 1.4.2

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text





```

## Logs

```text
Add your logs here.
```

**Comment by KapJI** [comment]
Can you show how Alarms screen looks like on that device?
