### ISSUE TITLE
[dev] Implement timers/alarms updates

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-google-home#24]
## Describe the bug

You still have to reload the integration to update timers and alarms, i dont know why and have tried a lot to fix it but it is over my skill level ;)

**Comment by ArnyminerZ** [comment]
I believe it has something to do with the way you have implemented refresh through the update coordinator. Shouldn't it be done through the `update` or `async_update` methods of the sensor (Check [docs](https://developers.home-assistant.io/docs/core/entity)). I've never worked with the update coordinator as you have done. I usually do it through those methods, and it usually works well, so maybe it's that. I may be able to take a look to it more deeply this afternoon.

**Comment by DurgNomis-drol** [comment]
I only build upon @leikoilja, and i have also never used the coordinator. So i hoped that @leikoilja  knows something about it 😊

**Comment by leikoilja** [comment]
Hm, I actually tested the coordinator and it was working when i first implemented it, so it was refreshing the sensors periodically. But hey-ho, so many things were changed, that this might not be working correctly yet 😄  I m back to my home-setup in a week and will be able to focus a bit more on this one. I simply don't have RPi/Google Home at hands to play and test it around with :) If someone has any interest - feel free to grab it, maybe someone can find what's wrong with it in a meanwhile :)

**Comment by DurgNomis-drol** [comment]
No hurry, there are other aspects like delete functions that i will look into in the meanwhile 😁

**Comment by ArnyminerZ** [comment]
Ok, I have finally managed to get a valid installation of Home Assistant working with `ha-google-home`. The error I'm getting is:
```
WARNING (SyncWorker_5) [custom_components.ha-google-home] Failed to fetch timers/alarms information from device ***. Will try again later.
```
I'm pulling latest changes to take a look.

**Comment by DurgNomis-drol** [comment]
This because zeroconf have been disabled, we need to implement HA zeroconf instead of using zeroconf from glocaltokens. As of know we have no way of determining the IP of each device. And that's is why you get that error.

**Comment by ArnyminerZ** [comment]
Ok, so we should implement the builtin `zeroconf` discovery?

**Comment by DurgNomis-drol** [comment]
Yes, but I haven't found that much information on how to yet

**Comment by ArnyminerZ** [comment]
Home Assistant's documentation is a bit peculiar... I'd check the source code of the Cast integration and adapt it to match our needs.

**Comment by DurgNomis-drol** [comment]
Your absolutely right about that 😆

That probably then easiest way, but I'm not that good at python (yet), do you mind taking a crack at it?

**Comment by ArnyminerZ** [comment]
Also, I believe the devices are loaded well in `ha-google-home`, since the Home Assistant log shows:
```
2021-02-25 15:06:59 DEBUG (SyncWorker_4) [glocaltokens.client] Google Home devices: [<glocaltokens.client.Device object at 0xeabf8f10>, <glocaltokens.client.Device object at 0xeabf8c58>, <glocaltokens.client.Device object at 0xeabf8838>, <glocaltokens.client.Device object at 0xeabf8568>, <glocaltokens.client.Device object at 0xeabf8538>, <glocaltokens.client.Device object at 0xeabf8808>, <glocaltokens.client.Device object at 0xeabf87a8>, <glocaltokens.client.Device object at 0xeabf8ad8>]
```
The thing that I'm not sure about is why the `glocaltokens.client.Device` class doesn't get formatted to dict, since `__str__` is implemented. Will take a look, this would show us whether or not the IP and port get loaded.

**Comment by ArnyminerZ** [comment]
> 
> 
> Your absolutely right about that 😆
> 
> That probably then easiest way, but I'm not that good at python (yet), do you mind taking a crack at it?

Yeah, of course, I'm taking a look rn. I think it should be working even with the `zeroconf` issue, but not sure.

**Comment by DurgNomis-drol** [comment]
Turn on debug and it will show you slot more info from the integration

**Comment by ArnyminerZ** [comment]
Nevermind, I was using a pretty outdated version 🤦🏼 now I see everything clearier.

**Comment by leikoilja** [comment]
I'm flying back to my setup coming Saturday, so will jump in some of those tickets pretty soon as well 💥  Thanks for taking a loot at it, @ArnyminerZ

**Comment by DurgNomis-drol** [comment]
@ArnyminerZ if there's is anything I can help with, I'm here

**Comment by ArnyminerZ** [comment]
I've found this warning when added the `zeroconf` dependency to the integration:
```
2021-02-25 15:56:02 WARNING (SyncWorker_2) [homeassistant.helpers.frame] Detected integration that attempted to create another Zeroconf instance. Please use the shared Zeroconf via await homeassistant.components.zeroconf.async_get_instance(hass). Please report issue to the custom component author for ha-google-home using this method at custom_components/ha-google-home/api.py, line 49: return self._client.get_google_devices(disable_discovery=False)
```
I've already opened a new [pr](https://github.com/leikoilja/glocaltokens/pull/34) to `glocaltokens` for implementing this. Waiting to @leikoilja to approve it and start testing.

**Comment by DurgNomis-drol** [comment]
Does this mean that if your PR is merged in glocaltokens, then we don't have to build zeroconf here and we can just pass it through to glocaltokens? 😊

**Comment by ArnyminerZ** [comment]
Yeah, I hope so. Everything should work well, we should only need to modify the `api.py` function of `GlocaltokensApiClient` to something like:
```python3
async def get_google_devices(self, hass: HomeAssistant):
    """Get google device authentication tokens.
    Note this method will fetch necessary access tokens if missing"""
    zeroconf_instance = await zeroconf_get_instance(hass)
    return self._client.get_google_devices(zeroconf_instance=zeroconf_instance)
```
And then, of course, modify the callers.

**Comment by DurgNomis-drol** [comment]
I'm ready to test as soon as there is something 😁 Great job @ArnyminerZ !

**Comment by leikoilja** [comment]
Great find, @ArnyminerZ! 🥳 
We'll probably need to new release of `glocaltokens` package, right? If so, i ll generate one tonight. Please make sure to bump the `manifest` dependancy to the appropriate version. It's just going to be a patch, so just increment the last digit, like  `glocaltokens==0.2.3`

**Comment by ArnyminerZ** [comment]
Yes, a new package should be released, so `ha-google-home` can use the new feature.

**Comment by leikoilja** [comment]
Done ✅

**Comment by DurgNomis-drol** [comment]
I just tried too incorporate passing the instance through to glocaltokens using the code written above and i dont know how to make it work. It complains about `'coroutine' object is not iterable`. when using it in ` def get_google_devices_information(self, hass):`?

Do we need to rewrite it all too be async or ? (We probably should)

```python
async def get_google_devices(self, hass: HomeAssistant):
    """Get google device authentication tokens.
    Note this method will fetch necessary access tokens if missing"""
    ha_zeroconf_instance = await zeroconf_get_instance(hass)
    return self._client.get_google_devices(zeroconf_instance=ha_zeroconf_instance)
```

```python
def get_google_devices_information(self, hass):
    """Retrieves devices from glocaltokens"""
    _LOGGER.debug("Fetching data...")
    offline_devices = []
    devices = self.get_google_devices(hass)
```

**Comment by ArnyminerZ** [comment]
Since you are calling an async function, for iterating it you should await it, and to await it, `get_google_devices_information` should be also async. This is a bit strange if you haven't worked with async functions. To sum up, you should change this:
```python3
async def get_google_devices_information(self, hass):
    """Retrieves devices from glocaltokens"""
    _LOGGER.debug("Fetching data...")
    offline_devices = []
    devices = await self.get_google_devices(hass)
```
And search for all the functions that call `get_google_devices_information`, and work asyncronously with them. This afternoon I may take a look at it.

**Comment by DurgNomis-drol** [comment]
I run in to this error (See below) after i have done what you describe above. 

```python
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ha-google-home/sensor.py", line 17, in async_setup_entry
    for device in coordinator.data:
TypeError: 'coroutine' object is not iterable
```
Python code it fails in: 
```python
async def async_setup_entry(hass, entry, async_add_devices):
    """Setup sensor platform."""
    coordinator = hass.data[DOMAIN][entry.entry_id]

    for device in coordinator.data:
        if device.local_auth_token:
            async_add_devices(
                [
                    GoogleHomeAlarmSensor(coordinator, entry, device),
                    GoogleHomeTimerSensor(coordinator, entry, device),
                    GoogleHomeSensor(coordinator, entry, device),
                ]
            )
```

And i can't find any information in HA about how to handle it when using async

**Comment by ArnyminerZ** [comment]
Should take a finer look, but can you try something like awaiting that `coordinator.data` call? Something like:
```python3
async def async_setup_entry(hass, entry, async_add_devices):
    """Setup sensor platform."""
    coordinator = hass.data[DOMAIN][entry.entry_id]

    for device in await coordinator.data:
        if device.local_auth_token:
            async_add_devices(
                [
                    GoogleHomeAlarmSensor(coordinator, entry, device),
                    GoogleHomeTimerSensor(coordinator, entry, device),
                    GoogleHomeSensor(coordinator, entry, device),
                ]
            )
```
Not sure about this, just wondering
