### ISSUE TITLE
Error in the log each time I start HA

### ISSUE THREAD

**Issue by Rocologo** [leikoilja/ha-google-home#248]
I get the error in the log each time I start HA, 

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:567
Integration: Sensor (documentation, issues)
First occurred: 10:45:50 AM (1 occurrences)
Last logged: 10:45:50 AM
Platform google_home does not generate unique IDs. ID Google Home/device already exists - ignoring sensor.google_home_device

```

And the sensors is unavailable

![image](https://user-images.githubusercontent.com/1008133/120774563-b0297900-c522-11eb-8761-60f865fa208c.png)

**Comment by ArnyminerZ** [comment]
As @Raul-7-7 has stated, please, @Rocologo we need some more info. Take a look at the [troubleshooting guide](https://github.com/leikoilja/ha-google-home#collecting-useful-log-data) to enable the extended logging, and paste some logs here.
Also, please, state the environment you are at, your HA version, and the integration's version.

**Comment by KapJI** [comment]
I think what's going on here is we use device name for unique id and you have devices with the same names: "Google Home". We need to use something more unique for unique id, e.g. internal device id, serial number or mac address.

**Comment by leikoilja** [comment]
For tracking purposes [here](https://github.com/leikoilja/glocaltokens/issues/75) is the ticket for unique id generation

**Comment by Rocologo** [comment]
Hi Guys. 

Sorry for not getting fast back to you. I had alot of problems with Home Assistant after installing HACS + Sonoff Lan + you Google addon. My HA started to make reboots without warnings, and after me trying to solve the basic problems, I ran into "disk full" on my NUC. And then my HA crashed totally. Luckily I had I backup, so I decided to make a total restore of HA, and because I did not really use HACS, Sonoff LAN + your addon, I decided not to install these Addons again. 

So.... Im not able to reproduce the problem anymore. Im sorry. 

I think the ticket for the unique Id is a good idea, because I had Google Home in my HA before I added your addon, so I looked like a confict with this 

https://www.home-assistant.io/integrations/google_assistant/ 

I have made a manual install of this integration and are able to speak to all my devices in HA using this, but this also broke when I installed your addon. 

Im not sure if you need this anymore, but I feel I owe you this: Im running HA in this setup.

A NUC running Linux/Debian fully updated. Virtualbox 6.1 and I have downloaded the vdi from here: https://www.home-assistant.io/installation/linux

Before crashing HA was fully updated with newest OS, Supervisor and Core

Kind regards
Rocologo

**Comment by ArnyminerZ** [comment]
Thank you very much @Rocologo, we will take your info into account. We are working on fixing the multiple ID issue. Hope you don't have any more issues. Greetings.
