### ISSUE TITLE
[dev] Implement delete function for timers and alarms

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-google-home#28]
They use the same endpoint to delete them

I have some code that works, but have to be modified to work with this integration.

I will make pull request soon with this feature.

**Comment by leikoilja** [comment]
@DurgNomis-drol is there any reason why you are closing it?

**Comment by DurgNomis-drol** [comment]
It is a duplicate of this #59 discussion. But we can keep it open if it is

**Comment by leikoilja** [comment]
oh, you are right, sorry completely missed it 😄 thanks for spotting it

**Comment by DurgNomis-drol** [comment]
No problem! 😄
