### ISSUE TITLE
Unable to set alarm volume 

### ISSUE THREAD

**Issue by gary-reyes** [leikoilja/ha-google-home#282]
The Readme indicates that something like the following should be available, number.living_room_alarm_volume. 

I do not see this anywhere in all the entities available anywhere. In fact this is the first time that I've heard number be HA domain. 

I am running with 2021.7.0b0 with version 1.5.0 of the integration.

**Comment by ArnyminerZ** [comment]
The number is a valid entity type, you can take a look at the [docs](https://developers.home-assistant.io/docs/core/entity/number). But will take a look to see what's wrong with the integration.

**Comment by gary-reyes** [comment]
Any update on this?

**Comment by leikoilja** [comment]
@gary-reyes have you got any logs you can share? Check README for troubleshooting and try restarting your HA keeping an eye on the logs for the initialization process of the Google Home integration. Post here your logs as block quote so we get a better understanding what is going on :)

**Comment by leikoilja** [comment]
Also discovered a weird thing in the source.
@ArnyminerZ on line: https://github.com/leikoilja/ha-google-home/blob/8e24b9605db062b0cd548c78ceab5ecd4a58f4d2/custom_components/google_home/api.py#L334

It calls out to fetch alarm volume setting but checks for `JSON_NOTIFICATIONS_ENABLED ` in response. I believe it's a typo and has never actually worked. Should it not be `JSON_ALARM_VOLUME`? 🤔 😅

**Comment by gary-reyes** [comment]
Should I still bother with getting logs?

Only entities I have are alarm sensor, timer, sensor, device sensor, and dnd switch


Can I at least get a confirmation that it should be created or that someone has it?

**Comment by leikoilja** [comment]
@gary-reyes you wanna help us check and fix it? :) Feel free to fork the repo, change the line I suggested and copy the entire integration directory to your HA instance. Then restart and it will load up the modified version of integration. Check if it works and if so - open up a pull request to help fixing the issue :)

**Comment by gary-reyes** [comment]
I think it's very narrow minded to assume that I would have the ability to even do something like that in the first place. I am trying to help fix the issue by contributing to the investigation 
 phase. Developing is not the way to help. 

I have reported an issue and I have asked if this is reproducible with everyone else since there shouldn't be any special steps to perform. It should literally be going to the google home integration page in home assistant and confirming that an entity exist. I have numerous Google home entities of various models and generations and none display this entity.

You, as the lead developer, use this integration yourself., I would assume. Could you see if this entity is present in that page?  It's not that I am being difficult or refuse to get logs, I do not want to get logs if the feature itself doesn't work or has never worked in the first place. If it happens to not work, the big advertisement for this feature should be removed from the feature set. 

![Screenshot_20210815-031849](https://user-images.githubusercontent.com/36871757/129472022-1a0d1e25-1d9f-4a06-8e0f-6f4eb4f26eb6.png)

**Comment by ArnyminerZ** [comment]
> Should it not be `JSON_ALARM_VOLUME`? 🤔 😅

Yeah, I totally think so, I may have missed that one. I currently don't have any access to my home's Home Assistant's installation. Can any of you try to make that fix?

**Comment by ArnyminerZ** [comment]
Well @gary-reyes, you have to understand that this project is not related to Home Assistant in any aspect, and all of us are involved here because we are passionate, and try to provide quality content. Every feature added goes through a hard development process, with multiple changes involved, just so code is more maintenable for everybody, and this may just be an typo that managed to get through the validation process, but was working on first instance, so I don't think is very fine of you to start blaming everyone just because you don't want to provide any logs.
Logs are the only way that we as developers have to find bugs and fix them. Asking for logs is our base method of investigation, since most of the times errors are directly specified on them. And yes, maybe this time the issue is a feature that is not working for anyone, but you shouldn't be refusing to give any logs if what you want is to get helped, just saying.
Anyway, this issue will be addressed ASAP, since at least us try to help in any way. Hope you understand this.

**Comment by gary-reyes** [comment]
I'm not trying to blame anyone. I can see how it could have across as that and am sorry for it. I understand how the development process works which is why I was asking "is this reproducible?" I understand the value of logs. In this particular case, the reproducibility should have been obvious on any system, if it was an issue affecting everyone. I thought in this particular case, they might have been unnecessary.

I completely understand how something could have been working and then it wasn't. However, something like this found by QA. In the original feature request which I opened, there wasn't any confirmation that it worked, the issue was just closed. This is not my project, so it can be managed as how you guys want. If this is an actual typo, I am surprised something as obvious wasn't even noticed by the development team and the rest of the community.

**Comment by leikoilja** [comment]
uuu, it's getting heated here 😄 
@gary-reyes, just as Arnau mentioned, we are all here volunteers trying to enjoy the journey and contribute to the open source projects. 
The reason I tried encouraging you to take a look at playing around with a line of code is that i had no access to my HA instance at the time of writing. Plus, encouraging other people taking pro-active measures has indeed helped to inspire some people to pick up challenges, ultimately helping this integration to grow :) I'll push a quick fix today and test to make sure it fixes the problem before we release a new minor version :)

**Comment by leikoilja** [comment]
Thanks, @ArnyminerZ for the review and merging.
I have tested it with `master` branch version and can confirm it worked. 
Will go out with the next release (probs sometime this week), I wanted to implement unique ID as well soon, so it could go in together :)
