### ISSUE TITLE
Google Wifi Control

### ISSUE THREAD

**Issue by ikrowni** [leikoilja/ha-google-home#289]
**Is your feature request related to a problem? Please describe.**
Google is migrating google wifi into google home. It would be great to be able to control the google wifi devices internet connection through switches and also be able to see useful data of each device connected along with speed test data.

**Describe alternatives you've considered**
I've used the home assistant integration for google wifi but its not very consistent. Sometimes i would switch the internet to a device off through home assistant only to see nothing had changed in the google wifi app and the connection was still working to that device.

**Comment by leikoilja** [comment]
That would be nice to add WiFi controls to this integration as well. @ikrowni, unfortunately none of the developers currently working on this integration seem to have Google WiFi devices to play around with, so if you have an interest in contributing - you are very welcomed to. We have an amazing team around who would be happy to help and assist you in that as much as we can. Just open a pull requests and we would help as much as possible :)

**Comment by ikrowni** [comment]
I'd certainly be willing to help where i can. i dont have any coding experience really but if your team can walk me through what to do then ill do what i can.

**Comment by KapJI** [comment]
There's already a custom integration for that, please try it out: https://github.com/djtimca/hagooglewifi
