### ISSUE TITLE
Feature request/ problem automations based on state

### ISSUE THREAD

**Issue by skank01** [leikoilja/ha-google-home#335]
I'm trying to make automations based on state of the alarm
When the alarm is ringing , the music has to play
When the alarm is snoozed or turned off, the morning routine should start

However, i'm having troubles making this, cause of the integration is polling every 180 seconds.
I now i can make it faster but as you said, it becomes unreliable, so i dont want too

Is there a way that polling happens when state changes?
Or can i have a workaround for this?

**Comment by KapJI** [comment]
Unfortunately, there is no way to do this before we figure out why local API starts timing out after more frequent requests or before Google just fixes this issue on their side.

**Comment by skank01** [comment]
Hi thx for replying.
Damn thats a pity.
I google aware of this?

**Comment by skank01** [comment]
Maybe its better to make automations then that starts as soon as the time from the alarm has reached + ... seconds

**Comment by KapJI** [comment]
> Is google aware of this?

Probably not. This local API is not documented and only intended to use for Google Home app.

**Comment by leikoilja** [comment]
@skank01, as @KapJI has mentioned unfortunately this is Google limitation. But we still encourage you to playing with pooling frequency. Some of us had good reliable results even with as small pooling results as 1 second. However when you do it, give the devices a few hours in between the changes cause this is about the time you start noticing devices timing out. Perhaps you can try cutting the frequency half to 90sec first, leaving it for 24h to make sure nothing broke and devices are not timing out (keep an eye on logs) and if everything is still fine - cut the frequency half again and check etc :)
