### ISSUE TITLE
Support for broadcasts

### ISSUE THREAD

**Issue by kiall** [leikoilja/ha-google-home#352]
**Is your feature request related to a problem? Please describe.**

Support for broadcasting to Google Home devices would be very useful. Broadcasts have an advantage over e.g. using tts aimed at the `media_player.device_name` entity, as it won't stop any music from playing.

**Describe the solution you'd like**

A new service and notifications integration to trigger a broadcast to Google Home devices.

**Describe alternatives you've considered**

This other project works, and I've used it in the past, however I'm not using HassIO any more, and would prefer not to add yet another container :)

https://github.com/AndBobsYourUncle/hassio-addons/tree/master/google-assistant-webserver

**Additional context**

**Comment by ArnyminerZ** [comment]
This is already implemented in the [Google Cast](https://www.home-assistant.io/integrations/cast/) integration. I believe this is not the focus of this integration in particular, so you should use Google Cast.

However, I think it's interesting to merge the two projects together, though I don't think Home Assistant would be really interested on this change, since the focus of the integrations is different. I leave the conversation open for other contributions.

**Comment by mbrevda** [comment]
Can you explain how one can use the Google Cast integration to broadcast a message without interrupting the currently playing media?

**Comment by kiall** [comment]
> Can you explain how one can use the Google Cast integration to broadcast a message without interrupting the currently playing media?

That's the thing - you can't use the Google Cast integration to send an audio message without interrupting music. It'll always stop the music. 

There's a separate Broadcast feature, and that one can be used. The project I linked above is a Home Assistant OS Addon that implements it - however I'm not on Haas OS anymore, and don't want to switch back - hence would prefer an integration like this one would add the feature :)

**Comment by ArnyminerZ** [comment]
> 
> 
> Can you explain how one can use the Google Cast integration to broadcast a message without interrupting the currently playing media?

I really believe that is not possible. As far as I understand, the "Cast feature" works by telling the device, for example a Google Home, where to play the music from, and it's the Google Home who makes all the requests, so there's no way of modifying the stream of data, or overlapping another one.

The only possible way is the one stated by @kiall, by using the broadcast command, but I don't think it's possible with the Homegraph API, which is as far as I'm concerned the only one provided by Google.

But the API is not open, people keep reverse-engineering it to get all the endpoints, but it might still be incomplete, so I can't help on this one. Maybe try opening an issue at the [Home Assistant](https://github.com/home-assistant/core/tree/dev/homeassistant/components/cast)'s repository, and they might have a better answer for this.

**Comment by ArnyminerZ** [comment]
Stale issue closed. Reopen if more info is required.
