### ISSUE TITLE
local_auth_token must follow the correct format

### ISSUE THREAD

**Issue by CallumCVM** [leikoilja/ha-google-home#355]
## Describe the bug

After setting up according to the guides, I use my 2fa token and email (I have tried every combination of this), but nothing happens after completing the integration. In the logs I see:

`2021-10-05 10:50:53 ERROR (SyncWorker_1) [glocaltokens.client] [Device - Nest Wifi router(id=160e82a2-9eb2-4e9a-9e44-8eb390d31d08)] local_auth_token must follow the correct format`

## Version of the integration

v1.8.1

## Logs
[log.txt](https://github.com/leikoilja/ha-google-home/files/7284765/log.txt)

**Comment by leikoilja** [comment]
Thanks for reporting the bug, @CallumCVM.
The bug ticket is already opened for the same topic here - https://github.com/leikoilja/ha-google-home/issues/348.
Please keep an eye on that thread for the fix and updates 💥  Should be fixed soon :)
