### ISSUE TITLE
Failed to fetch timers/alarms information from device

### ISSUE THREAD

**Issue by BossHuso** [leikoilja/ha-google-home#402]
## Describe the bug

I have everything set up as described and succesfully integrated within HA. But I can't get my devices.

One important note perhaps, is that HA is running on a server **not** within my home network. I saw some other issues where the logs of the Google devices return a local IP. If this is the case, I get that it won't work. But since my Google Home app can access the devices from every network, I thought it should be possible with this integration as well?

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
Latest pulled from git, so I'm guessing that counts as Release v1.9.1
```

## Logs

```text
2021-11-28 16:13:20 DEBUG (MainThread) [custom_components.google_home] Failed to fetch timers/alarms information from device Zara's kamer. We could not determine its IP address, the device is either offline or is not compatible Google Home device. Will try again later.
2021-11-28 16:13:20 DEBUG (MainThread) [custom_components.google_home] Failed to fetch timers/alarms information from device Babykamer. We could not determine its IP address, the device is either offline or is not compatible Google Home device. Will try again later.
2021-11-28 16:13:20 DEBUG (MainThread) [custom_components.google_home] Failed to fetch timers/alarms information from device Woonkamer. We could not determine its IP address, the device is either offline or is not compatible Google Home device. Will try again later.
2021-11-28 16:13:20 DEBUG (MainThread) [custom_components.google_home] Failed to fetch timers/alarms information from device TV. We could not determine its IP address, the device is either offline or is not compatible Google Home device. Will try again later.
```

**Comment by DurgNomis-drol** [comment]
You would need to set up routing between each network, but that is out of scope for this integration. 
The reason that the Google Home app can see your devices is because it can connect to them through the cloud. This integration communicates directly with each device. We only connect to Google servers to authenticate and get the auth token for each device. Besides that, we use mdns to discover devices (There IP address). That will also not work if not connected to the same network or not routed correctly between each. I believe other people have had similar issues with HA (not this integration) and you can probably find more info on how to set it up on the forums. If set up correctly, this integration should work just fine. Hope this helps you in the right direction. 😊

**Comment by BossHuso** [comment]
> You would need to set up routing between each network, but that is out of scope for this integration. The reason that the Google Home app can see your devices is because it can connect to them through the cloud. This integration communicates directly with each device. We only connect to Google servers to authenticate and get the auth token for each device. Besides that, we use mdns to discover devices (There IP address). That will also not work if not connected to the same network or not routed correctly between each. I believe other people have had similar issues with HA (not this integration) and you can probably find more info on how to set it up on the forums. If set up correctly, this integration should work just fine. Hope this helps you in the right direction. 😊

Ah okay, that makes sense. Thanks for the quick response. I tried some things like port forwarding on my router so the Google Nest Hub is accessible from my public IP, but that doesn't work since the Hub just refuses all calls outside the network.

I'm trying to make it work now by setting up a VPN on my home network and connect the HA docker to a OpenVPN docker.

All these things just to get the Ring Doorbell working together with my Google Nest Hub..

**Comment by DurgNomis-drol** [comment]
I am curious, why are you HA server outside you home network?

**Comment by BossHuso** [comment]
Because I have servers which run in a data center and none running in my home network.
