### ISSUE TITLE
Create & move static documentation 

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#408]
It would be great to move the documentation from `README` file to a dedicated docs

I have already enabled the github pages with build-in theme ( can be seen [here](https://leikoilja.github.io/ha-google-home/)), but it's very limited with no navigation capabilities.

Perhaps we can use Sphinx or smth like that?
There is an interesting read:
https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/
but would require some setup like github actions to generate docs and python Sphinx

Does anyone has any knowledge or interest in how to do it? :)

**Comment by DurgNomis-drol** [comment]
I am also interested in how to do this. I tried to add it sometime ago to another project I made, but didn't manage to finish it. I believe a requirement for generating docs with sphinx or other software is you need to annotate your code like this: https://github.com/DurgNomis-drol/mytoyota/blob/1d4cc568af0daa71fa8bc9e8828152c10da42bad/mytoyota/client.py#L127 This links to how i have done it in my code, though it could probably be done a lot better 😄

**Comment by KapJI** [comment]
I don't think we need auto-generated documentation for code.
Github wiki can do the job but it makes harder to accept PRs for it.
So simple `TROUBLESHOOTING.md` in repo root should be fine.
