### ISSUE TITLE
Ability to pause/skip/disable an alarm

### ISSUE THREAD

**Issue by gcorgnet** [leikoilja/ha-google-home#416]
**Is your feature request related to a problem? Please describe.**
Use case: I have a recurring Alarm going off every day at 5am and Im normally here to turn if off. Every once in a while, I'll go away for a weekend and will forget to disable it.

**Describe the solution you'd like**
It woud be nice if we had a way to automate toggling on/off a particular Alarm via Home Assistant. (I would probably use the scheduler then to disable it on the days I know I won't be around and re-enable it the following day, etc.)

**Describe alternatives you've considered**
I was hoping that Do Not Disturb (which can be set through automation) would give me this but unfortunately Alarms still go off when Do Not Disturb is on.
Alternative would be deleting the alarm and re-creating it but it doesn't look like there's a simple way to recreate it

**Additional context**
Using this on a Lenovo Smart Clock 2, if that's of any importance.

Would be happy to help tinker/test this.

**Comment by DurgNomis-drol** [comment]
This is not possible unfortunately, we can only delete alarms/timers. Right now there is no API endpoint for editing/controlling alarms and timers. ☹️

**Comment by gcorgnet** [comment]
How unfortnate. Thanks for confirming this though

**Comment by KapJI** [comment]
Basically we can do what Google Home app can. Pausing is not available there.
