### ISSUE TITLE
server error after update to HA 2022.2.1

### ISSUE THREAD

**Issue by lecrams** [leikoilja/ha-google-home#454]
After update to version 2022.2.1 I get the following error: "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble". Till this update everything was fine.
trying to reinstall I get exactly the same error. Has something changed with the update?
Any idea how to solve this?

**Comment by KapJI** [comment]
Duplicate of https://github.com/leikoilja/ha-google-home/issues/453.
