### ISSUE TITLE
1.9.7 no media_player entities created during integration

### ISSUE THREAD

**Issue by derekpurdy** [leikoilja/ha-google-home#458]
## Describe the bug

No media_player entities were created during integration

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.9.7
```

## Logs

```text
n/a
```

**Comment by derekpurdy** [comment]
ok, sorry. perhaps this doesn't do the media_player part and the google cast integration handles that. new to home assistant, so sorry for the ticket if not needed.

**Comment by DurgNomis-drol** [comment]
Yes this is the wrong integration 😊
