### ISSUE TITLE
Configuration flow could not be loaded: [Object Object]

### ISSUE THREAD

**Issue by Timo2208** [leikoilja/ha-google-home#467]
Config flow kon niet geladen worden: [object Object]

Configuration flow could not be loaded: [Object Object]

did add the debug view but dont get the log files's

when adding the integratin its giving this message

**Comment by leikoilja** [comment]
What version of the home assistant, what version of the integration and what version of HACS are you trying to use? What system are you on?

**Comment by leikoilja** [comment]
Can confirm the issue. Now running the integration in the local dev container I can see:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/10655107/155582447-97b7924b-fd8e-4007-af2f-a72a50f592f4.png">

in logs when trying to install `Google Home` integration

**Comment by leikoilja** [comment]
Fixed and released in [v1.9.8](https://github.com/leikoilja/ha-google-home/releases/tag/v1.9.8) 💥
