### ISSUE TITLE
Google Home integration does not show up at HASS integrations after installing from HACKS

### ISSUE THREAD

**Issue by tnrclkr** [leikoilja/ha-google-home#481]
<html>
<body>

HACKS : 1.23.0
Home Assistant 2022.3.3

Google Home integration installed by HACKS but no integration app at hass configuration / integrations / add integrations section.

what can fix or where to check?

--

<br class="Apple-interchange-newline">
</body>
</html>

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
Add version here.
```

## Logs

```text
Add your logs here.
```

**Comment by leikoilja** [comment]
Have you restarted your HomeAssistant instance after installing the integration, @tnrclkr?

**Comment by tnrclkr** [comment]
Yes, First restarted server then restarted host completely to be sure, but no result. i can see the files in custom components folder

**Comment by leikoilja** [comment]
@tnrclkr check your logs, unfortunately, there is nothing we can help with a limited info and no way to replicate

**Comment by leikoilja** [comment]
@tnrclkr, I m closing this stake issue. Please provide more information for us to help replicate and fix it :)
