### ISSUE TITLE
Alarm state format

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#50]
## Problem
In #47 alarm state format was changed from unix timestamp to formatted string which is nice and makes it more readable. But I think it should also include time zone because it's a local time. 

Before March 28 I live in UTC and can't check this but Sweden uses CET and I believe if in template editor in developer tools you try this, these timestampts won't be equal:
```
Converted timestamp: {{ as_timestamp(states("sensor.<google_home_name>_alarms")) }}
Fire time: {{ state_attr("sensor.<google_home_name>_alarms", "alarms")[0]["fire_time"] }}
```
This makes it harder to use state in automations.

## Solution
Add time zone to `TIME_STR_FORMAT`. `%z` should be compatible with ISO datetime format. It should look like `2021-03-04 13:41:04+0100`

**Comment by leikoilja** [comment]
Hmmm, do you think "state" should be a better time format like ISO for easier automation?
Because now we have 'local time' and 'utc' time in attributes one can hook into. 

![image](https://user-images.githubusercontent.com/10655107/109973615-eaebfd00-7cf8-11eb-95f3-a4bd7a83853f.png)

**Comment by KapJI** [comment]
Another option I see is just to make state "on" or "off". It's probably more in line with other home assistant components.

**Comment by KapJI** [comment]
But anyway adding time zone to `local_time` is a good idea. And in this case I don't see why to keep `date_time_utc`.

**Comment by leikoilja** [comment]
Both of those sounds really nice. Let's split those into two issues. One to sort the alarms, another to fix the state format.
The tricky part with alarms is that they can be single or repetitive, that integration does not cater for yet. 
Let's keep this issue to fix state to provide ISO time, we ll keep `local_time` for UI references and remove `utc` time :)

**Comment by KapJI** [comment]
So,
1. Make state `on` and `off`
2. Add time zone to `local_time`

Do I get it correctly?

**Comment by leikoilja** [comment]
haha, sorry i got confused myself for a second 😄  
Totally agree on 1 and 3. How about keeping `local_time` as is and adding `local_time_iso`?
