### ISSUE TITLE
Fails to fetch IP through zeroconf

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-google-home#51]
## Version of the custom_component

Latest master

## Configuration

```yaml
2021-03-04 17:12:47 DEBUG (MainThread) [custom_components.ha-google-home] Failed to fetch timers/alarms information from device Kitchen. We could not determine it's IP address, the device is either offline or is not compatable Google Home device. Will try again later.
```

## Describe the bug

It fails to fetch IP through zeroconf. Device is on and a timer is set. Device is a Google Nest Mini

While setting up the integration it finds my device, but i does not when trying to fetch data from it.

## Debug log

See above

**Comment by leikoilja** [comment]
@DurgNomis-drol I am wondering if there might be problems with your zeroconf being inside Docker. You need to double check all the ports are open both for your container and OS you are hosting on.

**Comment by DurgNomis-drol** [comment]
🤦 You are right, I just tested it on my main HA instance and it works fine. I just forgot that my test server was not using host, but a bridge interface instead. I will close this. Thanks for the help

**Comment by leikoilja** [comment]
No problem! ;) Do you mind adding that into README to warn others? :)

**Comment by DurgNomis-drol** [comment]
Yes i will do that 😄
