### ISSUE TITLE
Reuse android_id

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#54]
## Version of the custom_component
Latest `master` branch 

## Describe the bug
When performing google requests to fetch tokens we should provide **one and the same** android_id, without generating a new id every time. If we do - it will look like dozens of different devices are connected to the same account that might lead to unexpected authentication problems. 
We already have some mitigation in the underlying `glocaltokens` python package, but we need a more robust mechanism, because now when Homeassistant restarts it will also restart `glocaltokens` instance wiping away stored `android_id` that will lead to fetching a new one.

We are already saving `android_id` in the integration config flow (`CONF_ANDROID_ID: await client.get_android_id()`), but we never use it. We should either introduce `set_android_id()` method in underlying `glocaltokens` that we would call every sensor update cycle (just to be sure) or pass that value when calling `get_google_devices`.

@ArnyminerZ, would you have any interest in picking it? 🙏 🥇 😄

**Comment by leikoilja** [comment]
@DurgNomis-drol, @ArnyminerZ could any of you help me with this one? I think it should be one of the last things really affecting the stability/robustness of the package. After open PR and this gets merged I believe we should be ready for long awaited first release 😅🤩💥 then we can bring in some testers

**Comment by DurgNomis-drol** [comment]
I think this should be handled in `glocaltokens` and not `ha-google-home` (like you describe with a method called `set_android_id()` in `glocaltokens`). This would be useful to other applications that depends on `glocaltokens` and then we just pass it back like you have described in `get_google_devices(android_id) `.

**Comment by DurgNomis-drol** [comment]
See my [PR](https://github.com/leikoilja/glocaltokens/pull/39) in `glocaltokens`.

**Comment by ArnyminerZ** [comment]
This weekend I won't be able to do much work, but if anyone picks it, I'll do it pleasantly next week 😄

**Comment by leikoilja** [comment]
No problem, @ArnyminerZ! Super happy you are contributing, so whenever you I have time and interest, feel free to grab any open issues 🤩💥

**Comment by leikoilja** [comment]
@DurgNomis-drol, thanks for picking it up and starting working on it!

Thing is that you don't necessarily need to add an optional android_id argument to 'get_google_devices'. Please see the config flow file, what we already do there is that when you first add the integration the config flow saves 3 variables in its config: google login, google password and android id.
Since generating that id is a static method of the Glocaltokens class, we generate the android id and save it in the HA config for the integration.

So what I propose is we use that android id from the config when we initialize API client.

**Comment by DurgNomis-drol** [comment]
I just tested if it actually does reuse android_id after a restart and it does. But can you please confirm by adding:
```python
async def get_google_devices_information(self, zeroconf_instance):
    _LOGGER.debug("Android id: {id}".format(id=self._android_id))
```
Because as far as i can see in our code it does reuse it.

It passes it here:
```python
class GlocaltokensApiClient:
    def __init__(
        self,
        hass,
        username: str,
        password: str,
        session: aiohttp.ClientSession,
        android_id: str,
    ) -> None:
        """Sample API Client."""
        self.hass = hass
        self._username = username
        self._password = password
        self._session = session
        self._android_id = android_id
        self._client = GLocalAuthenticationTokens(
            username=username, password=password, android_id=android_id <--
        )
```

Also why do we generate a android id in ha-google-home, when we never use it?

**Comment by leikoilja** [comment]
Oh, flip.... We are indeed already reusing the android id from the config: 
In `__init__.py`:
```python
    android_id = entry.data.get(CONF_ANDROID_ID)

    session = async_get_clientsession(hass, verify_ssl=False)

    glocaltokens_client = GlocaltokensApiClient(
        hass, username, password, session, android_id
    )
```
dohhh, I'm so sorry, @DurgNomis-drol, completely missed it out, my fault. It was me who implemented it 6 weeks ago and i completely forgot about it. Sorry for wasting your time 😞 😄

**Comment by DurgNomis-drol** [comment]
No problem 😄 I learn a lot from these things, so i didn't waste any time

**Comment by leikoilja** [comment]
That's an awesome attitude, @DurgNomis-drol! 🚀
