### ISSUE TITLE
GLIBC_2.34 not available  Home Assistant version 2022.6.0

### ISSUE THREAD

**Issue by blackest** [leikoilja/ha-google-home#543]
## Describe the bug

Error occurred loading configuration flow for integration google_home: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by /home/john/homeassistant/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so)

## Version of the integration
 v1.9.11 , v1.912
If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
Add version here.
```

## Logs

```text
Add your logs here.
```

**Comment by leikoilja** [comment]
hmm, @blackest, never seen an issue such as yours. I wonder what platform are you running your home assistant instance? It looks like grpc can't compile on your machine

**Comment by blackest** [comment]
it was working ok on 2022.5.5 but when i upgraded to 2022.6.0 it was fine and then i saw the update for 1.912 and then it went downhill, i reverted to 1.911 which had been working and i checked to see if glibc2.34 was available and only glibc2.33 was. it maybe that raspberrian will update to 2.34 later and then i can use the extension but i think trying to upgrade to 2.34 can break a lot of stuff so i think i am going to have to wait.

**Comment by milandzuris** [comment]
same

**Comment by TheMcBain92** [comment]
Currently having a similar issue.

Error occurred loading configuration flow for integration google_home: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /srv/homeassistant/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so)

**Comment by blackest** [comment]
Looks like some tough choices need to be made. I think i'm right in saying that all rasbian images are basically "bulls eye" or debian stable non of these images has GLIBC_2.34 and it's probably fair to assume it could be a long time before this would change.  Maybe switching to unstable might resolve the issue.  Not looked to be fair.

However there is ubuntu 22.04 (64 bit) GLIBC_2.35 is onboard Python3 is 3.10.4 rust is 1.6 something I think 1.41 is needed.  Of course that's not just moving homeassistant to the ubuntu platform  there is everything else that has been installed over the years as well, that will need configuring as well. 

I like running core but its obvious HA devs would prefer us all to be using their containers. There has also been a few other changes such as no default PI user and password. I was able to dd an image to an SD card on the PI from the PI but even after using touch SSH i had no account to login with so had to hook up a monitor keyboard and mouse ...   

Anyway it looks like the solution is the uncomfortable one of installing a new OS and then reconfiguring HA from scratch. I think i can do the rebuild on an SD Card and when its complete clone it over to my SSD, that way i can have a working system and then move to the upgraded one when i'm ready. Just my thoughts on this and i am not an expert.

**Comment by blackest** [comment]
> ```
> pip install -U grpcio==1.46.1 --no-binary=grpcio --force-reinstall
> ```

Yes this works for me, had to go to myaccount.google.com to generate an app password but this works for Home Assistant Core 2022.6.6  Python 3.9

of course the next problem will be to upgrade to python 3.10 and a 2022.7.x release...

**Comment by blackest** [comment]
> I don't think you need to use Python 3.10 just yet. Python 3.9 should be perfectly fine.

You are correct sir, I successfully updated core to 2022.7.5 with minimal breakage. :)
Thank you.

**Comment by leikoilja** [comment]
Thanks @KapJI for investigating and adding description to README 🔥 💪
