### ISSUE TITLE
HA BETA - 2022.7.0b0 - Deprecation Warnings

### ISSUE THREAD

**Issue by jazzyisj** [leikoilja/ha-google-home#562]
## Describe the bug

Depracation warnings in HA v2022.7.0b0

## Version of the integration

1.9.13

## Logs

`2022-06-29 19:45:05 WARNING (MainThread) [homeassistant.components.number] custom_components.google_home.number::AlarmVolumeNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.`

**Comment by leikoilja** [comment]
Thanks for the report, @jazzyisj 💥

**Comment by KapJI** [comment]
List of deprecated methods: "async_set_value", "max_value", "min_value", "set_value", "step", "unit_of_measurement", "value". I guess we should use `_attr_*` instead.

@DurgNomis-drol @ArnyminerZ anyone is interested in fixing this?
