### ISSUE TITLE
Add refresh setting to configuration 

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#58]
**Is your feature request related to a problem? Please describe.**
Currently the integration updates timers/alarms at a hardcoded period (15 seconds or 5 minutes). 

**Describe the solution you'd like**
A configuration UI setting where the user can set a custom update rate. Maybe with some reasonable limits.

**Comment by KapJI** [comment]
I don't think we actually need this. 10 seconds is reasonable interval for everyone.

**Comment by leikoilja** [comment]
Perhaps you are right :) We can revisit it if that will be needed, but as you say 10 sec is most likely gonna do great for most! :) Thanks!
