### ISSUE TITLE
Introduce services to delete/modify alarms or timers

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#59]
**Is your feature request related to a problem? Please describe.**
When one wants to make automation he needs to know what is the soonest timer/alarm to go off. Also when the user wants to delete/modify an alarm/timer how does one do that? 

**Describe the solution you'd like**
We should probably look into introducing HA [services](https://developers.home-assistant.io/docs/dev_101_services) with a separate service for each task, like: 
- delete alarm (input: alarm id) See [API docs how to](https://rithvikvibhu.github.io/GHLocalApi/#operation/DeleteAlarmsandTimers)
- delete timer (input: timer id) [API docs how to](https://rithvikvibhu.github.io/GHLocalApi/#operation/DeleteAlarmsandTimers)

@DurgNomis-drol , @ArnyminerZ, @KapJI what do you think about that idea? Would any of you have an interest in implementing that? 🥳

**Comment by DurgNomis-drol** [comment]
Delete is the same endpoint, so i think it should just be one service, and you can also delete multiple at a time.

Can you explain the reasoning(Of where it will be usable) behind a service that get the next alarm/timer, instead of just always have next alarm be the state of `sensor.living_room_alarms`? (Only asking because i'm curious) 😄 

Here is a the way i did it in my previous integration: 
```python
def delete(self, id):
        url = 'https://' + self.device_ip + ':8443/setup' + ENDPOINT + '/delete'
        header = {'cast-local-authorization-token': local_token,
                  'content-type': 'application/json'}
        data = {"ids": [id]}

        response = requests.post(url, data=json.dumps(data), headers=header, verify=False, timeout=TIMEOUT)

        if response.status_code != HTTP_OK:
            _LOGGER.error("API returned {}".format(response.status_code))
            return

        result = response.json()

        if result['success'] != True:
            _LOGGER.error("API returned success false")
            return
```

**Comment by leikoilja** [comment]
It seems like having the next alarm/timer in the state of the sensor is not really Home Assistant way of doing things. Mostly the purpose of the sensor is to provide data in a useful way "as is", so that can be further utilized in automation/frontend etc. So the frontend or automation would do all the logic of how to extract and present that data. That way no data is lost or limited from integration, all is just provided from the backend leaving room for data manipulation for other stakeholders :) 
But then I can clearly see how important it would be for everyone to know what is their next time/alarm, so the service seems more of a HA way of doing things. I might be wrong thou haha

**Comment by KapJI** [comment]
I think for next timer and next alarm we just need to sort them in state attributes during updates, there is no need for a dedicated service for that. Services should perform some action like deleting or modifying an alarm.

**Comment by leikoilja** [comment]
I was thinking it might get tricky with next alarm when it comes to recurring alarms, but that actually doesn't matter where to implement that logic in the service or in the sensor state attributes. So let's do it as you propose - in the sensor state attributes, so the first out is the next alarm.

Some tricky scenario to consider:
For example:
- It's Friday now
- First alarm is recurring on Sundays at 7am
- Second alarm is tomorrow at 8am
So the sorting should cater to extract that the next alarm is the second one

**Comment by KapJI** [comment]
Yes, for recurring alarms we should use time when it will fire next time.

**Comment by KapJI** [comment]
Delete alarm should also accept `entity_id` of alarm or `device_name`. Same for delete timer.

**Comment by DurgNomis-drol** [comment]
@KapJI Yes, that what but a very HA way of doing it. And very easy to make it share the same implementation in the backend

@leikoilja I think you are right about that we should do it in th HA way. Should we think about implementing a separate sensor that only have the next alarm time as a state. So we can use it like the alarm sensor that are created from the mobile apps?

**Comment by leikoilja** [comment]
uuu, i actually like the idea of a whole new sensor which job is to be "next alarm", just like mobile apps provide for android. 
@KapJI, what do you think?

**Comment by KapJI** [comment]
I'm not convinced in how useful it is. It seems to me that simple sorting of alarms should be enough. What problem are you trying to solve?

**Comment by leikoilja** [comment]
I'm an ios user, but if i understand correctly android users have a sensor called `next_alarm` which is already widely used in automations etc. So what @DurgNomis-drol is proposing is creating a similar sensor which would be a plug-and-play solution for many users, without the need to fetch the first alarm from the list of alarms from a sensor. I'm just thinking how easy/hard it would be in automations to get "next alarm" if we need to get first element from the list of alarms

**Comment by DurgNomis-drol** [comment]
It would be very HA-like to make it conform to that format. I use my alarms sensor from my phone to trigger sunrise light and other things I want to do when i wake up 😊

**Comment by leikoilja** [comment]
Lucky android users 😄

**Comment by DurgNomis-drol** [comment]
😆 I actually thought that the IOS app also had sensors.

It is one of the most used features for me

But I don't think it is important to implement that right now, and could easily be a release v2(or 3)

**Comment by leikoilja** [comment]
So what is our consensus on this one? 
@KapJI, do you have any arguments why sorting would be a better way to go? 
Let's find common grounds and create a separate issue for implementing "next alarm" either by sorting of a new sensor type

**Comment by DurgNomis-drol** [comment]
I think we should sort alarms in the normal sensor for alarms and then implement a new sensor (down the line) that only lists the next alarms ala the same style the mobile app does 😊

**Comment by KapJI** [comment]
Yes, for convenience `next_alarm` sensor may be useful. But alarm list still need to be sorted, otherwise it's not very useful.

**Comment by leikoilja** [comment]
Agreed, and we can probably reuse the same logic under the hood for both the sensor and the list of alarms. @DurgNomis-drol can you please help creating a new issue with the stuff we discussed here regarding next alarm? :)

**Comment by DurgNomis-drol** [comment]
I'm not home right now, but will do it later to night 😊

**Comment by leikoilja** [comment]
@KapJI, would you be interested in implementing it #63?

**Comment by KapJI** [comment]
@DurgNomis-drol already started it in #65 🙂

**Comment by ronschaeffer** [comment]
Firstly, thanks for this integration! I've missed having the timer info since the previous method stopped working.

Is someone working on a delete time/delete alarm service? I'd love to test it if so,

**Comment by DurgNomis-drol** [comment]
I have some code, but i have been busy squashing bugs, and some other projects. :smile: Hopefully i will find time to make a PR for it soon.

**Comment by lolouk44** [comment]
happy to help test deletion / creation of alarms too.
I used this a lot on a previous (non google/nest) alarm where an automation would turn the alarm off when left home and enable it when I came back. This was to avoid waking the wife when I was away on a business trip
I understand it's not possible to turn alarms on and off on a nest hub, but being able to create delete would be a nice workaround

**Comment by DurgNomis-drol** [comment]
Only delete is possible 😊 i will hopefully look into it tomorrow or Sunday 😊

**Comment by lolouk44** [comment]
I feared it might be the case, and if so I might toy with recording my voice asking G to create my alarms, then have this played on a speaker nearby, see if I can trick it into creating alarms this way ;)
