### ISSUE TITLE
Google +

### ISSUE THREAD

**Issue by moovy2** [leikoilja/ha-google-home#591]
## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
Add version here.
```

## Logs

```text
Add your logs here.
```

**Comment by moovy2** [comment]
> 
> 
> ## Describe the bug
> 
> 
> 
> ## Version of the integration
> 
> If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).
> 
> 
> 
> ```text
> Add version here.
> ```
> 
> ## Logs
> 
> 
> 
> 
> 
> ```text
> Add your logs here.
> ```
>

**Comment by leikoilja** [comment]
@moovy2, sorry your issue report is incomplete and impossible to derive what you meant by opening it. I ll close it for now
