### ISSUE TITLE
Feature Request: Light sensor in Google Home/Nest Hub

### ISSUE THREAD

**Issue by OptimusGREEN** [leikoilja/ha-google-home#609]
I've just found this custom component and as it stands I probably wouldn't use it. A feature that would definitely make me. use it would be the ability to get the data from the google home hubs light sensor. Is this something that could be possible?

**Comment by leikoilja** [comment]
@OptimusGREEN, there is no such google product as "hubs light sensor" as far as i know. 
What you need, is to understand what light sensor/platform are you using and use the corresponding integration. 
If it's Philips Hue you are using - you have gotta go with https://www.home-assistant.io/integrations/hue/
If you are using Ikea Tradfri - https://www.home-assistant.io/integrations/tradfri/

**Comment by OptimusGREEN** [comment]
Hi,

I'm talking about the light sensor built into the Google home hub or Google nest hub. 

Cheers

**Comment by leikoilja** [comment]
ou, sorry, misunderstood you then :) let's reopen it as a feature request

**Comment by KapJI** [comment]
I doubt there is a way to get data from that sensor. If you know something about API for it, please provide more details.

Of course, it's up to you whether to use this integration or not.

Closing for now.
