### ISSUE TITLE
Setup failed for custom integration google_home: Requirements for google_home not found: ['glocaltokens==0.6.7'].

### ISSUE THREAD

**Issue by edwardtich1** [leikoilja/ha-google-home#612]
Logger: homeassistant.setup
Source: setup.py:184
First occurred: 08:34:09 (1 occurrences)
Last logged: 08:34:09

Setup failed for custom integration google_home: Requirements for google_home not found: ['glocaltokens==0.6.7'].

integration not loaded

can't delete

how to delete manually?

**Comment by leikoilja** [comment]
Try deleting `google_home` directory from `custom_components` directory on your HA instance. Then install it again using HACS store. The issue you are seeing about `glocaltokens==0.6.7` means that you have an outdated version of `ha-google-home` integration on your home assistant.
