### ISSUE TITLE
Add ability to set a new timer.

### ISSUE THREAD

**Issue by rml1111** [leikoilja/ha-google-home#613]
Google Nest Hubs have a great timer interface, which I would like to use in a couple of different locations in my house (kitchen and home gym), however, I would like to be able to use a zigbee button press to trigger a Home Assistant automation to set a timer on the Nest Hub, eliminating the need to repeatedly issue verbal instructions to the device to set a new timer. 

I have done significant research and trial and error (e.g. the now deprecated Assistant Relay) to no avail. If the google home APIs support adding a new timer/changing existing timer, then it would be a very valuable feature to add to this integration. 

Many thanks for your work this great integration!

**Comment by Drakulix** [comment]
The google-home integration mostly relies on the ["Google Home Local Api"](https://rithvikvibhu.github.io/GHLocalApi/) to provide its functionality, which is what the Google Home App internally uses.
And sadly that api does only expose functions to get and delete timers (or alarms for that matter), but not to create or modify them.

Also alarms and timers are local to these devices and internally likely implemented by some device specific actions.
So you won't be able to create or set timers using solutions such as Assistant Relay as well, as those do not communicate with or via the Nest Hubs, but directly with googles servers via the Google Assistant SDK.
And they don't have any knowledge about set timer or alarm functions on your nest hubs.

So sorry, this is not possible (at least not with the APIs we know of).
