### ISSUE TITLE
Why is this not in core?

### ISSUE THREAD

**Issue by HarvsG** [leikoilja/ha-google-home#615]
**Describe the solution you'd like**
Is there any plan for this custom integration to make it into core one day?

**Describe alternatives you've considered**
I've looked through issues and discussion section to see if this has been asked before. I'm sure it must have been but I can't find it.

**Additional context**

**Comment by DurgNomis-drol** [comment]
Not at this moment 😃 

1. It's all a bit finicky, so it will be hard to provide a stable UX. 
2. It would require moving large parts of the code to a new package, as direct IO is not allowed in the integration code in HA.

**Comment by HarvsG** [comment]
Ok 👍

**Comment by DurgNomis-drol** [comment]
@HarvsG Unfortunately the finicky bits will continue as long as this uses an unofficial API in a way that was never intended

**Comment by leikoilja** [comment]
True that, thanks @DurgNomis-drol for breaking it. Also the initial reason to have it as a separate integration was to allow the team to iterate through releases faster :)
