### ISSUE TITLE
Timers never show in home assistant from Nest Hub display

### ISSUE THREAD

**Issue by dnestico** [leikoilja/ha-google-home#641]
## Describe the bug

I have been using timers on my nest hub displays since basically day 1, media works fine in home assistant, the problem is Alarms and Timers never show up in home assistant.

I have a 20 minute timer set right now, and the timer sensor for that device just shows this:

**This entity is no longer being provided by the google_home integration. If the entity is no longer in use, delete it in settings.**

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

``` v1.9.15 according to HACs ```

## Logs

```
I do not have debug logs enabled.
```

**Comment by leikoilja** [comment]
@dnestico i am afraid we cannot do much without logs from your installation. There might be many various things affecting why the sensors are not pulling the data correctly, but to be able to understand what causes it for you - you'd need to provide logs and more information

**Comment by dnestico** [comment]
So I turned on debug logging and changed the update interval and it's suddenly working today wtf?? lol.

Also there is nothing in the logs even with debug logging enabled so not sure what I can give you.

**Comment by leikoilja** [comment]
hm... please check the `README` about how to enable the logging, but since that is not longer an issue, let's close it.
If the issue happens again, feel free to reopen and drop some more info here :)
