### ISSUE TITLE
async_setup_platforms will fail in version 2023.3

### ISSUE THREAD

**Issue by chicknlil** [leikoilja/ha-google-home#648]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 7:43:47 PM (2 occurrences)
Last logged: 7:44:09 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for google_home using this method at custom_components/google_home/__init__.py, line 78: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by KapJI** [comment]
This will be fixed in the next release.

Duplicate #640.
