### ISSUE TITLE
Exclude certain devices

### ISSUE THREAD

**Issue by tungmeister** [leikoilja/ha-google-home#673]
Currently there's no way to delete or exclude devices - I have 15+ google home devices however I'd only like to use the functionality of the integration with 2 of them. I'd like to be able to delete all the devices I don't want to monitor reducing the traffic/queries from the integration.

**Comment by leikoilja** [comment]
@tungmeister have you tried in-build HA functionality to "Enable device" on the entity?

**Comment by tungmeister** [comment]
I haven't but if you're saying that will totally disable the devices and stop them being queried in the back ground then i'll use that method.

**Comment by leikoilja** [comment]
I can confirm that by disabling the entity in HA - no more sensors are being updated and no more API calls done to google home devices :) 
![image](https://user-images.githubusercontent.com/10655107/224554300-fc531f98-b045-407a-92f7-5c811bda5e8c.png)

**Comment by tungmeister** [comment]
Great, I'll disable the unneeded devices then.
