### ISSUE TITLE
Google home reminders and alarms no longer available...

### ISSUE THREAD

**Issue by tom-lejeune** [leikoilja/ha-google-home#674]
After a crash and reinstall of backup I couldn't use my Google home speaker entities anymore. The alarms and reminder-entities were marked as unavailable and gave the message "entity is no longer being provided by the integration" . Reload didn't help. I removed and reinstalled Google home integration, now I only have 1 entity per speaker, no more alarms/reminders/...

In diagnose the IP address seem to have switched to ipv6 adresses instead of ipv4. (See attachement)
![Screenshot_20230303-230745](https://user-images.githubusercontent.com/2422652/222838852-a176b544-6d24-46ae-af79-3cbb3d9ca598.png)
Nothing I tried so far has brought back the alarms an timer integration.
Tried setting a reminder for a couple of hours on the speaker itself, but never gotten a reaction in home assistant

**Comment by jgverweij** [comment]
Same problem since update to v.1.19.17
Reverted back to v1.19.16 and they're back again.

**Comment by ben209car** [comment]
I'm having the same issue.  Volume increases, the google sound is heard, but the announcements don't work.  My MP3 file for my door bell also don't work.

Any update??

**Comment by tom-lejeune** [comment]
> I'm having the same issue. Volume increases, the google sound is heard, but the announcements don't work. My MP3 file for my door bell also don't work.
> 
> Any update??

that's a total different issue.

this issue resolved itself, the IP6 reverted to IP4 and everything works now.
