### ISSUE TITLE
Last executed command

### ISSUE THREAD

**Issue by eric1905** [leikoilja/ha-google-home#688]
I would love to be able to determine which of my google homes executed a script in Homeassistant so I can respond to this specific device. Unfortunately I don't know which device sent a command. 

Is there any possibility to provide a timestamp or a flag that the device is currently executing a command / executed a command at a specific time, so I can use this attribute?

**Comment by leikoilja** [comment]
Which command do you mean when you say "google home executed a script/command in Homeassistant"? 
this integration doesn't enable speakers to control HA instance, but rather other-way around: enables Homeassistant to read and change timers/alarms/DND of the speakers

**Comment by eric1905** [comment]
I don't want to control the HA instance. I would be happy when I say.
"Hey google, turn the light off"
or something like this, that I can read out from the timestamp from the speaker when this command was said.

**Comment by leikoilja** [comment]
@eric1905 what you are looking for is another integration
https://www.home-assistant.io/integrations/google_assistant/
which is part of the HA core, so you'd need to take it over there
