### ISSUE TITLE
Rename component

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#69]
# Problem
`ha-google-home` is not [PEP8 compliant name](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) for python module. It should use `_` for spaces.

This is only 1 of 2 custom components with `-` here: https://github.com/home-assistant/wheels-custom-integrations/tree/master/components

All components in home assistant follow this rule: https://github.com/home-assistant/core/tree/dev/homeassistant/components

# Can we rename the whole thing?
I understand it's quite a huge change but it's better to do this earlier.
But this is also an opportunity to choose a better name. Can we use just `google_home` or it's too bold? 🙂
There is no official `google_home` component anymore, so this name should be free.

# What needs to be renamed
- https://github.com/home-assistant/brands/pull/2317
- https://github.com/home-assistant/wheels-custom-integrations/pull/313
- This folder: https://github.com/leikoilja/ha-google-home/tree/master/custom_components/ha-google-home
- Entries in [`manifest.json`](https://github.com/leikoilja/ha-google-home/blob/master/custom_components/ha-google-home/manifest.json)
- Documentation
~~-Repo renaming (GitHub automatically redirects within the same domain to the updated repo name).~~
  ~~- (edit from Ilja) Update link references in @DurgNomis-drol's card [here](https://github.com/DurgNomis-drol/ha-google-home-timers-card)~~
  ~~- (edit from Ilja) Update link references on HA community forum [here](https://community.home-assistant.io/t/solution-to-track-your-google-home-alarms-and-timers-and-trigger-different-home-assistant-events/61534/87)~~

**Comment by leikoilja** [comment]
uuuu, i see where we messed up with dashes in the name 😄  Had a discussion early on at #19.
I can see the benefit of what you are proposing, and would be up for a challenge. Especially this early on with nearly no people yet using it. I have added two bullet points to the "TODO" list and I believe if we pull the forces together and split the tasks we should be quite able to do it with the minimum amount of hassle :)
@ArnyminerZ, @DurgNomis-drol you guys in? 💥 👨‍💻

**Comment by DurgNomis-drol** [comment]
I'm all for it! 😄 

I will take [home-assistant/brands#2317](https://github.com/home-assistant/brands/pull/2317) and my own card.

**Comment by leikoilja** [comment]
Sounds great! Let's reference this ticket everywhere where needed then. 
I'll take the repo renaming; community forum reference update; and all references around the code (incl directory name and manifest).

@KapJI would you like to help opening PR at home-assistant/wheels-custom-integrations#313 (i guess after this repo is renamed) and updating documentation?

**Comment by KapJI** [comment]
@leikoilja sure, I can do that!

**Comment by leikoilja** [comment]
Thank you both, @KapJI, @DurgNomis-drol, it went surprisingly quick to rename the entire thing 🚀 💯
