### ISSUE TITLE
Enable authorisation through Google's Advanced Protection Program (GAPP)

### ISSUE THREAD

**Issue by Bodge-IT** [leikoilja/ha-google-home#699]
**Is your feature request related to a problem? Please describe.**
I've just enrolled to Google's [Advanced Protection Program (GAPP)](https://landing.google.com/advancedprotection/) and discovered with that extra security there are a lot of services/apps etc that do not know of it or are not capable of connecting.  Even apps like Tripit amongst them. 

The symptoms look like the "you don't have 2FA enabled on your account" symptoms but in the GAPP, 2FA is not enabled/disabled, it's on by default and uses hardware-based tokens.

**Describe the solution you'd like**
I would like for the Google Home integration provide access through GAPP.  GAPP uses hardware-based security through Yubikeys or Google's own.  It is possible as Bluemail offers continued access to my GMAil(following reauthorisation).

**Describe alternatives you've considered**
Un-enrolling from enhanced security but this never seems like a good idea especially with all the latest session token security breaches that seem popular right now.

**Additional context**
I understand that this integration probably relies on the underlying library for its capabilities but maybe that could be enhanced too to offer increased security.

**Comment by leikoilja** [comment]
This sounds to be generally good idea, but might be hard to get around all the hardware used to home homeassistant. Perhaps that should come as a top-down implementation support starting from homeassistant core supporting it and once supported - we can start by adding it to [`glocaltokens` authentication library](https://github.com/leikoilja/glocaltokens) used by this package
