### ISSUE TITLE
Can not login after integration reinstall

### ISSUE THREAD

**Issue by lpt2007** [leikoilja/ha-google-home#710]
## Describe the bug

After upgrade haos to latest version I lost connection with google home my devices greyed out. Then I removed integration restart ha, clear browser, then I installed integration again using HACS. After I try to login I get error:

`Username/Password is incorrect. If your google account has 2FA enabled please generate app password (https://myaccount.google.com/apppasswords). If authentication still fails refer to https://github.com/leikoilja/ha-google-home#troubleshooting`

my ha version:
```
Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest
```

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.9.17
```

## Logs

```text
[!] Could not get master token.
```

**Comment by DavidFFerreira** [comment]
Same Here

**Comment by Adcop95** [comment]
Same issue here, getting same message in logs

`Logger: glocaltokens.client
Source: custom_components/google_home/api.py:73 
Integration: Google Home ([documentation](https://github.com/leikoilja/ha-google-home), [issues](https://github.com/leikoilja/ha-google-home/issues)) 
First occurred: 9 May 2023 at 23:40:20 (3 occurrences) 
Last logged: 00:19:25

[!] Could not get master token.`

**Comment by ChienTingLu** [comment]
I encountered the same problem after updating to Home Assistant 2023.5.2

**Comment by andeny** [comment]
i have encountered same issue when setting up a new instance of HA with 2023.5.2

**Comment by leikoilja** [comment]
This issue seems to be related to authentication `BadAuthentication` issue and unfortunately is difficult to replicate. I just tested the integration on 2 setups (macOs and RPi) and it worked just fine for both of those setups on the latest HA 2023.5.2.
I m going to close it and redirect to https://github.com/leikoilja/ha-google-home/issues/599 where more general discussion currently is regarding `BadAuthentication` with some findings. Please contribute there with logs/your setup

**Comment by leikoilja** [comment]
Great, so release v1.10.0 is out now :)
Anyone how has experienced issues with authentication using login/password, please update to the latest release and use `master_token` for authentication instead. 
[Here](https://github.com/leikoilja/ha-google-home#master-token) is the info on how to get the master_token before installing ha-google-home integration.
https://github.com/leikoilja/ha-google-home/releases/tag/v1.10.0
