### ISSUE TITLE
Google no longer supports the use of sign-in via third-party apps or devices with a username and password

### ISSUE THREAD

**Issue by jonathan-glass** [leikoilja/ha-google-home#716]
https://support.google.com/accounts/answer/6010255#zippy=%2Cuse-an-app-password
![image](https://github.com/leikoilja/ha-google-home/assets/66077595/bb72920f-024b-48aa-82fc-7f4837d65376)

According to this page, Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password. I believe this is the reason my app password fails to authenticate me when attempting to set up the integration.

**Comment by MPHxxxLegend** [comment]
`2023-05-11 19:18:46.040 ERROR (SyncWorker_2) [glocaltokens.client] [!] Could not get master token.
2023-05-11 19:18:46.048 ERROR (MainThread) [custom_components.google_home] `

![image](https://github.com/leikoilja/ha-google-home/assets/108364529/67c8312d-0620-468c-a19c-58552a8fd5c5)
![image](https://github.com/leikoilja/ha-google-home/assets/108364529/5f008208-c8b9-4775-956e-28eda3270bc9)

I am also unable to login, I am trying to the last 5 days with no success.

> https://support.google.com/accounts/answer/6009563 According to this page, Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password. I believe this is the reason my app password fails to authenticate me when attempting to set up the integration

Oh no, so the Integration is useless?

**Comment by Tymon3310** [comment]
i have same issue

**Comment by tsvi** [comment]
Same issue here

**Comment by jonathan-glass** [comment]
> I am also unable to login, I am trying to the last 5 days with no success.
> Oh no, so the Integration is useless?

Until it's possible to use oauth it's looking that way. 

I'm getting errors regardless of whether I use an app password with 2FA, or an account with just a standard username and password. 

![image](https://github.com/leikoilja/ha-google-home/assets/66077595/56fcc423-abb7-4a35-839e-d06b16aeae79)

**Comment by Brephlas** [comment]
Not sure if this related to the accouncement of google, since the deadline for the support was in May last year and the integration was working between then and now. 
Furthermore, this issue seems to be not present for everyone, as, for example, @leikoilja cant replicate this issue and is still able to authenticate: https://github.com/leikoilja/ha-google-home/issues/710#issuecomment-1542134804

**Comment by tae180** [comment]
Same issue here, not working for me.  Getting the same error message as others posted here.

**Comment by tsvi** [comment]
Can this be implemented using oauth? Like the existing Google integrations?

**Comment by leikoilja** [comment]
Great, so release v1.10.0 is out now :)
Anyone how has experienced issues with authentication using login/password, please update to the latest release and use `master_token` for authentication instead. 
[Here](https://github.com/leikoilja/ha-google-home#master-token) is the info on how to get the master_token before installing ha-google-home integration.
https://github.com/leikoilja/ha-google-home/releases/tag/v1.10.0

**Comment by uhTWO** [comment]
> Great, so release v1.10.0 is out now :)
> Anyone how has experienced issues with authentication using login/password, please update to the latest release and use `master_token` for authentication instead.
> [Here](https://github.com/leikoilja/ha-google-home#master-token) is the info on how to get the master_token before installing ha-google-home integration.
> https://github.com/leikoilja/ha-google-home/releases/tag/v1.10.0

This worked for me, but now I can't see any of my cameras. They're on another VLAN different from HA, but it's routable/reachable from HA.

**Comment by leikoilja** [comment]
@uhTWO check HA logs, but should not be related to this integration, since this integration does not support cameras
