### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by treforparr** [leikoilja/ha-google-home#717]
This is not integrating with home Home assistant  Hacs

**Comment by boekabart** [comment]
What a helpful bug report! I'm sure a dev will see this and say : oh boy, I know what's wrong now, I'll quickly fix it!

**Comment by leikoilja** [comment]
@treforparr, not sure what this issue is meant for, but i suspect that you might have authentication issues.
It is unfortunately ongoing issue with authentication and it's being discussed [here](https://github.com/leikoilja/ha-google-home/issues/599)
