### ISSUE TITLE
Cannot login - [!] Could not get master token.

### ISSUE THREAD

**Issue by fejjn** [leikoilja/ha-google-home#718]
## Describe the bug

Cannot login to Goole home from HA.

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
v1.9.17 of HA Google Home

HA:
Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest
```

## Logs

This error originated from a custom integration.
Logger: glocaltokens.client
Source: custom_components/google_home/api.py:73
Integration: google_home ([documentation](https://github.com/leikoilja/ha-google-home), [issues](https://github.com/leikoilja/ha-google-home/issues))
First occurred: 18:47:48 (4 occurrences)
Last logged: 18:55:38

[!] Could not get master token.

```text
Add your logs here.
```

**Comment by leikoilja** [comment]
There is unfortunately ongoing issue with authentication. It's already discussed [here](https://github.com/leikoilja/ha-google-home/issues/599)

**Comment by leikoilja** [comment]
Great, so release v1.10.0 is out now :)
Anyone how has experienced issues with authentication using login/password, please update to the latest release and use `master_token` for authentication instead. 
[Here](https://github.com/leikoilja/ha-google-home#master-token) is the info on how to get the master_token before installing ha-google-home integration.
https://github.com/leikoilja/ha-google-home/releases/tag/v1.10.0

**Comment by RobDrady01** [comment]
> Great, so release v1.10.0 is out now :) Anyone how has experienced issues with authentication using login/password, please update to the latest release and use `master_token` for authentication instead. [Here](https://github.com/leikoilja/ha-google-home#master-token) is the info on how to get the master_token before installing ha-google-home integration. https://github.com/leikoilja/ha-google-home/releases/tag/v1.10.0

I run the below in HA terminal 

https://hub.docker.com/r/breph/ha-google-home_get-token

it doesn't give me the token though...

Is there more steps required?

**Comment by leikoilja** [comment]
there should be no more steps required, @RobDrady01. 
but check out the https://github.com/leikoilja/ha-google-home/issues/599 thread first for more info around it and ping the Breph if container malfunctions

**Comment by KapJI** [comment]
@RobDrady01 it would help at least to see the error you're getting there.
