### ISSUE TITLE
Homeassistant docker with dependencies preïnstalled

### ISSUE THREAD

**Issue by Luttik** [leikoilja/ha-google-home#733]
**Is your feature request related to a problem? Please describe.**
The current description of how to install ha-google-home on ARM based devices (which I estimate is the majority of users) requires installing dependencies in the docker. Which should be done every time the docker is reinstalled or updated. Not only that, but this can take a while to load too.

**Describe the solution you'd like**
A home assistant docker image with the dependencies already installed. This saves people a lot of time.

**Work in progress**
I created a small docker-file with CD step to illustrate how this could work https://github.com/leikoilja/ha-google-home/pull/732.

**Comment by leikoilja** [comment]
added a question [here](https://github.com/leikoilja/ha-google-home/pull/732#issuecomment-1606909516)
