### ISSUE TITLE
a translation of Korean

### ISSUE THREAD

**Issue by iluna8** [leikoilja/ha-google-home#746]
`{
  "config": {
    "step": {
      "user": {
        "title": "Google Home \uC778\uC99D",
        "description": "\uAD6C\uC131\uC5D0 \uB300\uD55C \uB3C4\uC6C0\uC774 \uD544\uC694\uD55C \uACBD\uC6B0 \uC5EC\uAE30\uB97C \uCC38\uC870\uD558\uC2ED\uC2DC\uC624: https://github.com/leikoilja/ha-google-home. \uAD6C\uAE00 \uACC4\uC815 \uC0AC\uC6A9\uC790 \uC774\uB984\uACFC \uC571 \uC554\uD638\uB97C \uC0AC\uC6A9\uD558\uC2ED\uC2DC\uC624. \uC571 \uC554\uD638\uB97C \uC0DD\uC131\uD558\uC5EC \uC2E4\uC81C \uC554\uD638 \uB300\uC2E0 \uC0AC\uC6A9\uD558\uB294 \uAC83\uC774 \uB354 \uC548\uC804\uD558\uACE0 \uC27D\uC2B5\uB2C8\uB2E4. \uC77C\uBC18 \uC554\uD638\uC640 \uB3D9\uC77C\uD55C \uC561\uC138\uC2A4 \uAD8C\uD55C\uC744 \uAC00\uC9C0\uACE0 \uC788\uC9C0\uB9CC \uC2A4\uD06C\uB9BD\uD305\uD558\uB294 \uB3D9\uC548 \uC2E4\uC81C \uC554\uD638\uB97C \uC0AC\uC6A9\uD558\uB294 \uAC83\uBCF4\uB2E4 \uB354 \uC88B\uC2B5\uB2C8\uB2E4. (https://myaccount.google.com/apppasswords). \uADF8\uB807\uC9C0 \uC54A\uC73C\uBA74 \uC77C\uBC18 \uAD6C\uAE00 \uACC4\uC815 \uC554\uD638\uAC00 \uC791\uB3D9\uD574\uC57C \uD569\uB2C8\uB2E4.",
        "data": {
          "username": "Google \uACC4\uC815 \uC0AC\uC6A9\uC790 \uC774\uB984",
          "password": "Google \uACC4\uC815 \uC571 \uC554\uD638",
          "master_token": "Google \uACC4\uC815 \uB9C8\uC2A4\uD130 \uD1A0\uD070"
        }
      }
    },
    "error": {
      "auth": "\uC0AC\uC6A9\uC790 \uC774\uB984/\uBE44\uBC00\uBC88\uD638\uAC00 \uC798\uBABB\uB418\uC5C8\uC2B5\uB2C8\uB2E4. Google \uACC4\uC815\uC5D0 2FA\uAC00 \uD65C\uC131\uD654\uB418\uC5B4 \uC788\uC73C\uBA74 \uC571 \uBE44\uBC00\uBC88\uD638\uB97C \uC0DD\uC131\uD558\uC2ED\uC2DC\uC624 (https://myaccount.google.com/apppasswords). \uC778\uC99D\uC774 \uC5EC\uC804\uD788 \uC2E4\uD328\uD558\uB294 \uACBD\uC6B0 \uB2E4\uC74C\uC744 \uCC38\uC870\uD558\uC2ED\uC2DC\uC624 https://github.com/leikoilja/ha-google-home#troubleshooting",
      "pass-len": "Google \uC815\uCC45\uC5D0\uC11C \uC554\uD638 \uAE38\uC774\uB294 100\uC790\uB85C \uC81C\uD55C\uB429\uB2C8\uB2E4 (https://support.google.com/a/answer/139399). \uC554\uD638\uB97C \uBCC0\uACBD\uD558\uAC70\uB098 \uC571 \uC554\uD638\uB97C \uC0AC\uC6A9\uD558\uC2ED\uC2DC\uC624 (https://myaccount.google.com/apppasswords).",
      "missing-inputs": "\uC0AC\uC6A9\uC790 \uC774\uB984\uACFC \uC554\uD638 \uB610\uB294 \uB9C8\uC2A4\uD130 \uD1A0\uD070\uC744 \uC81C\uACF5\uD558\uC2ED\uC2DC\uC624",
      "master-token-invalid": "\uB9C8\uC2A4\uD130 \uD1A0\uD070\uC774 \uC798\uBABB\uB418\uC5C8\uC2B5\uB2C8\uB2E4. \uC804\uCCB4 \uD1A0\uD070\uC774 \uC9C0\uC815\uB418\uC5C8\uB294\uC9C0 \uD655\uC778\uD558\uC2ED\uC2DC\uC624 (\uD3EC\uD568\uD558\uC5EC 'aas_et/')"
    },
    "abort": {
      "single_instance_allowed": "\uB2E8\uC77C \uC778\uC2A4\uD134\uC2A4\uB9CC \uD5C8\uC6A9\uB429\uB2C8\uB2E4."
    }
  },
  "options": {
    "step": {
      "init": {
        "data": {
          "update_interval": "\uC5C5\uB370\uC774\uD2B8 \uAC04\uACA9 \uBCC0\uACBD. \uC7A5\uCE58 \uC2DC\uAC04 \uCD08\uACFC\uB85C \uC5B4\uB824\uC6C0\uC744 \uACAA\uB294 \uACBD\uC6B0 \uC774 \uAC04\uACA9\uC744 \uB298\uB9BD\uB2C8\uB2E4. \uAE30\uBCF8\uAC12: 180 (\uCD08)"
        }
      }
    }
  }
}`

**Comment by leikoilja** [comment]
@iluna8, i am going to close this dues to placing it in the incorrect place.
Please open a PR with the proposed changes, see [this PR](https://github.com/leikoilja/ha-google-home/pull/563/files) as an example of what needs to be done
