### ISSUE TITLE
Unable to generate Master or Access Tokens needed for Integration setup 

### ISSUE THREAD

**Issue by ghxstxch** [leikoilja/ha-google-home#752]
## Describe the bug

Unable to generate master token based on both glocaltokens & gpsoauth methods. 

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
master branch/v1.10.0 
Latest glocal/oauth packages 
```

## Logs

```text
N/A for home assistant, can't get set up
```
Result from attempting to run:
```
[!] Could not get master token.
Request response: {'Error': 'BadAuthentication'}

OR

It simply spits out "None" 
```

Environment is Docker on Debian 12 VM

**Comment by leikoilja** [comment]
as we have seen previously, this is quite possibly cause by incorrect dependency versions ending in the error for you.
Please try [this](https://gist.github.com/rithvikvibhu/952f83ea656c6782fbd0f1645059055d?permalink_comment_id=4640932#gistcomment-4640932) approach or install `urllib3<2.0.0` in isolation that should help you to get the master token.

**Comment by ghxstxch** [comment]
> as we have seen previously, this is quite possibly cause by incorrect dependency versions ending in the error for you.
> Please try [this](https://gist.github.com/rithvikvibhu/952f83ea656c6782fbd0f1645059055d?permalink_comment_id=4640932#gistcomment-4640932) approach or install `urllib3<2.0.0` in isolation that should help you to get the master token. 

I have attempted both of these already unfortunately, the docker method generated a 100GB+ docker container that broke the VM when it ran out of space (Backups are important, glad I made one beforehand!), installing urlib3<2.0.0 failed out, even after attempting it in a venv. Any advice?

**Comment by leikoilja** [comment]
wow, 100GB+ container :O how is that even possible from `python:3.9-slim-bullseye` image 😅 

you need to get urlib3 versioned <2.0.0, i m afraid there is no easy way to currently go about it, @ghxstxch. As you can see from https://gist.github.com/rithvikvibhu/952f83ea656c6782fbd0f1645059055d?permalink_comment_id=4632141#gistcomment-4632141 you need to install specific versions of deps for the auth request to go through

**Comment by ghxstxch** [comment]
> wow, 100GB+ container :O how is that even possible from `python:3.9-slim-bullseye` image 😅 
> 
> you need to get urlib3 versioned <2.0.0, i m afraid there is no easy way to currently go about it, @ghxstxch. As you can see from https://gist.github.com/rithvikvibhu/952f83ea656c6782fbd0f1645059055d?permalink_comment_id=4632141#gistcomment-4632141 you need to install specific versions of deps for the auth request to go through 

Admittedly, not sure, I'm confused myself but was able to reproduce it twice after breaking my VM initially, lol. Looks like I [may not be the only one](https://gist.github.com/rithvikvibhu/952f83ea656c6782fbd0f1645059055d?permalink_comment_id=4671023#gistcomment-4671023) either. 

I see someone's comment about using a Deb11 LXC, I can attempt this tomorrow and report back if I have any success. Missed that it might be OpenSSL too. I will try with a clean slate when I have time tomorrow. Thanks for the insight!

**Comment by leikoilja** [comment]
sorry for the hassle, google does not make it developer friendly or easy for 3rd parties to integrate 😓 😅 
let us know here, i think we lll need to revisit README to update with some more useful info
