### ISSUE TITLE
Master Token: None

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#755]
### Discussed in https://github.com/leikoilja/ha-google-home/discussions/754

<div type='discussions-op-text'>

<sup>Originally posted by **Woorkier** September 10, 2023</sup>
I was able to run the Python script in order to get the master token, but i always receive "none" as my master token.
```

[*] Getting master token...
[!] Could not get master token.
[*] Master token: None

[*] Getting access token...
[!] Could not get access token.
[*] Access token: None

[*] Done.
```
Tried using my own password and a generated app password, but none seems to work. Any ideas? Thanks!!</div>

**Comment by leikoilja** [comment]
@Woorkier, do you have any more logs or errors when you are loading tokens? 
both master and access tokens are `None` in your response above

**Comment by jamieshaw** [comment]
I'll tag onto this — finally getting around to fixing my Google Home authentication and hitting the same issue (I've neglected it's failed authentication for _a long while_).

I too am seeing the same when using the python script (with my credentials/app password added).
<img width="240" alt="image" src="https://github.com/leikoilja/ha-google-home/assets/16481433/2e9e6ea1-8bf1-492e-9743-fe838187d983">

**Comment by mossychop** [comment]
What can I do to help resolve the authentication issue? I can give you access or give you logs, whatever is needed. I really appreciate all the work you do but authentication seems to be broken for lots of people and it used to work really well.

**Comment by KapJI** [comment]
Authentication part is provided by [gpsoauth](https://github.com/simon-weber/gpsoauth) library, that's not something we actively support.

**Comment by mossychop** [comment]
> Authentication part is provided by [gpsoauth](https://github.com/simon-weber/gpsoauth) library, that's not something we actively support.

Which changed 3 weeks ago to API21, is this why email/password has stopped working? 

https://github.com/simon-weber/gpsoauth/issues/56#issuecomment-1687357144

**Comment by KapJI** [comment]
> Which changed 3 weeks ago to API21, is this why email/password has stopped working?

That commit is from similar but unrelated implementation in Go.

Gpsoauth hasn't been changed recently: https://github.com/simon-weber/gpsoauth/commits/master

**Comment by VNRARA** [comment]
I've been trying the whole night to get any tokens. Even with an account that doesn't have 2FA.

**Comment by leikoilja** [comment]
@VNRARA what did you try doing? See this [big issue](https://github.com/leikoilja/ha-google-home/issues/599) that talks about various ways how people got the master token (using docker image, for example).

I suspect this issue is totally related to https://github.com/leikoilja/ha-google-home/issues/599, so i will close this one in favour of the existing one
