### ISSUE TITLE
Master token

### ISSUE THREAD

**Issue by benixgil** [leikoilja/ha-google-home#764]
Sorry, new to this programing world. I can't figure it out how to get the master token. I don't know how the gettokens work, I don't know what program to use or how to. Is there any video, or something, so I can learn how to use this?
Every place I search, basically it's assumed I know the basics that I don't. I read everything, but don't know actually how to do them.
I have 0 knowledge in python, I looking for, or a step by step guide, or a dummies way to do it.
Thks in advance.

**Comment by leikoilja** [comment]
hey @benixgil. sorry to hear that it turns out to be a bit more complicated than it needs to be.
Check [this](https://github.com/leikoilja/ha-google-home/issues/599#issuecomment-1740931867) instruction that someone posted a few days ago using windows setup.

**Comment by marcootjehhh** [comment]
You link to some instructions on how to get the master token on windows, but the link is dead

**Comment by leikoilja** [comment]
Sorry, @marcootjehhh , it was a while back, so the link is gone now.
It wouldn't be any different getting tokens on mac or windows these days. Please see [README here](https://github.com/leikoilja/ha-google-home#master-token) , you will most likely prefer the docker way
