### ISSUE TITLE
Add missing docstrings

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#78]
# Problem
Let's enforce better documentation and add missing docstrings.
# How to do this
Remove these lines from `pyproject.yaml` and make sure `poetry run pylint custom_components/google_home` finished with no warnings.
```
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
```
Can anyone take this?

**Comment by DurgNomis-drol** [comment]
@KapJI I will take this (so i can learn how to use poetry). 😄 But i will probably first be able to look at it in the weekend, hope that is okay

**Comment by KapJI** [comment]
Sure, thank you! Poetry is pretty simple, just run `poetry install` and it will configure everything for you.
