### ISSUE TITLE
Getting the error: master_token doesn't follow the AAS_ET format

### ISSUE THREAD

**Issue by kaizersoje** [leikoilja/ha-google-home#812]
## Describe the bug

I am using HA 2023.12.2 and the google_home v1.10.2 . I used the Docker method to get the master token using the app password. The token was generated successfully.
I then tried to add the integration and then I get the following error in the log.

`2023-12-14 11:35:27.482 ERROR (MainThread) [glocaltokens.client] master_token doesn't follow the AAS_ET format`

I have tried out all possible combinations with/without `@gmail.com`, app password/account password, tripple checked for any blank spaces and etc but nothing worked out.

My master token is in the format:
```text
aas_et/AKppINabdfhtfy6ughnghjghjgjghbhhbnmnghjhjghjghjghjghjgh
```

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.10.2
```

## Logs

```text
2023-12-14 11:35:27.482 ERROR (MainThread) [glocaltokens.client] master_token doesn't follow the AAS_ET format
```

**Comment by KapJI** [comment]
The check is pretty simple.
1. Token must start with `aas_et/`
2. Token must be exactly 223 characters long.

Make sure you copied the whole thing.

**Comment by kaizersoje** [comment]
Yes, I did. I cropped it for the purpose of this ticket.

**Comment by kaizersoje** [comment]
When I pasted the token in MS Office Word, it tells me that there are only 203 characters. I have copied the token exactly as it was generated.

**Comment by KapJI** [comment]
Word is not the best tool for this, it can automatically replace some characters with something else. Try Notepad instead.

**Comment by kaizersoje** [comment]
I tried an online character count website as well. Same thing.

**Comment by kaizersoje** [comment]
Any advice @leikoilja?

**Comment by leikoilja** [comment]
this is the first time we heard that token length is 203 instead of 223 characters. @kaizersoje do you have access to any other accounts to check the length of the master token there? 
We can cater for 203 chars as well as 223, but we would need to know if it's google's new pattern? 🤔

**Comment by kaizersoje** [comment]
Hi @leikoilja I am away on holiday at the moment. So it will be a while I can look into this.

**Comment by pablitok** [comment]
Hi, I'm having a similar issue but my token is 224 chars long (checked with `echo 'aas_et/.....=' |wc -c`)
Before upgrading (I don't know from wich version to the last one) it was working well

**Comment by philou669** [comment]
> Hi, I'm having a similar issue but my token is 224 chars long (checked with `echo 'aas_et/.....=' |wc -c`) Before upgrading (I don't know from wich version to the last one) it was working well

me too my token have 224 chars long

**Comment by KapJI** [comment]
Probably we should relax this check a bit.

**Comment by philou669** [comment]
> Probably we should relax this check a bit, feel free to submit a PR. You will need to check that your token indeed works.

how I can check if my token works

![Sans titre](https://github.com/leikoilja/ha-google-home/assets/49702687/96f9041e-49de-413e-8d7f-8e1c3c46a986)

**Comment by KapJI** [comment]
> how I can check if my token works

You need to modify glocaltokens library here: https://github.com/leikoilja/glocaltokens/blob/master/glocaltokens/utils/token.py

And install modified version in order to test it.

**Comment by e1018e1018** [comment]
I found that it says Token must be exactly 223 characters long, which is not the same as my token.
Finally, I discovered that the token I copied had an EOL (end-of-line) character. After removing it, I successfully logged in.
Thanks for your help 😄
