### ISSUE TITLE
Danish translation spelling mistakes

### ISSUE THREAD

**Issue by zaprodk** [leikoilja/ha-google-home#814]
in custom_components/google_home/translations/da.json:

**Hvis**Vis du har brug for hjælp til at konfigurere, klik her: https://github.com/leikoilja/ha-google-home. Brug din Google kontos brugernavn og app-adgangskode. Det er **sikrere**sikre at generere en app-adgangskode i stedet for at bruge din normale adgangskode. App-adgangskode har adgang til det samme, men er bedre end din normale adgangskode når man bruger den i scripts. (https://myaccount.google.com/apppasswords). Du kan også bruge din normale adgangskode.

**Comment by leikoilja** [comment]
Hey, @zaprodk.
Thanks for contributing. Can you open a new pull request with the proposed changes to the translation file?
