### ISSUE TITLE
Alarms on Google Home devices don't show up.

### ISSUE THREAD

**Issue by satmandu** [leikoilja/ha-google-home#827]
## Describe the bug

My integration appears to pull up all of my Google Home devices (Nest Hub 2, Mini, Home Max, etc.), but the timers do not appear. I set a timer, i.e., "Hey Google, set a timer for 3 minutes," and then check the dashboard. The timers are marked as unavailable. I've tried adjusting the update interval on the integration to 15, which hasn't helped either.

This is what the dashboard shows even when I set timers:

![image](https://github.com/leikoilja/ha-google-home/assets/1096701/a5be050b-2a8e-4ac3-8f17-3be8538f72e5)

## Version of the integration

```text
1.11.0
```

## Logs

[glocaltokens.log](https://github.com/leikoilja/ha-google-home/files/14041863/glocaltokens.log)
[google_home.log](https://github.com/leikoilja/ha-google-home/files/14041843/google_home.log)

When I look at developer tools/states I do see settings which indicate that information is being pulled off of the devices, e.g.,

number.living_room_nesthub_alarm_volume

![image](https://github.com/leikoilja/ha-google-home/assets/1096701/c0952eae-b595-4c98-82ea-9b32d9432133)

**Comment by oeh-lsr** [comment]
Had the same issue. Reloading the integration seems to have solved it for me.

**Comment by chelming** [comment]
I did a reload and removed/readded it and I'm seeing the same thing. No errors and both sensors are unavailable.

**Comment by leikoilja** [comment]
thanks for the updates. will close it for now

**Comment by satmandu** [comment]
Reloading also fixed it for me...
