### ISSUE TITLE
Cant add google Home, probably the x user sry!

### ISSUE THREAD

**Issue by IIIdefconIII** [leikoilja/ha-google-home#848]
## Describe the bug
I have no  idea of 2 things the general token and the glocaltockens im running HA in a VM on a Synology NAS.
Im browing to intergrations / discovered and shows me google_home
When i setup the username / emailname@gmail.com
Ma de a app password not 100% sure if i need the spaces or witwhout
Example i got was : 1234 5678 0919 0123
I tried that and like 1234567809190123 so without the spaces
Master key, no idea how and where to get that to be honest
also unsure about that glocaltokens im reading stuff but i have no clue how to add this tbh

## Version of the integration
v1.11.0
as for as i see im on :latest-->

```text
Installed the Google Home HACS Package
```

## Logs
``
logger:
logger:
  default: warning
  logs:
    # log level for HA core
    homeassistant.core: fatal

    # log level for MQTT integration
    homeassistant.components.mqtt: warning

    # log level for all python scripts
    homeassistant.components.python_script: warning

    # individual log level for this python script
    homeassistant.components.python_script.my_new_script.py: debug

    # log level for SmartThings lights
    homeassistant.components.smartthings.light: info

    # log level for a custom integration
    custom_components.my_integration: debug

    # log level for the `aiohttp` Python package
    aiohttp: error

    # log level for both 'glances_api' and 'glances' integration
    homeassistant.components.glances: fatal
    glances_api: fatal

    custom_components.bureau_of_meteorology: debug

    custom_components.pyscript: info

    custom_components.google_home: debug
    glocaltokens: debug
-->

```text
These are the Google searches lines in the home-assistant.log.1
ValueError: unconverted data remains: :56
2024-03-24 20:50:00.193 ERROR (SyncWorker_6) [glocaltokens.client] [!] Could not get master token.
2024-03-24 20:50:00.201 ERROR (MainThread) [custom_components.google_home] 
2024-03-24 20:50:07.156 ERROR (SyncWorker_19) [glocaltokens.client] [!] Could not get master token.
2024-03-24 20:50:07.175 ERROR (MainThread) [custom_components.google_home] 
2024-03-24 20:52:12.602 ERROR (SyncWorker_2) [glocaltokens.client] [!] Could not get master token.
2024-03-24 20:52:12.604 ERROR (MainThread) [custom_components.google_home] 
2024-03-24 20:52:21.120 ERROR (SyncWorker_52) [glocaltokens.client] [!] Could not get master token.
2024-03-24 20:52:21.123 ERROR (MainThread) [custom_components.google_home] 
2024-03-24 20:52:24.912 ERROR (SyncWorker_30) [glocaltokens.client] [!] Could not get master token.
2024-03-24 20:52:24.915 ERROR (MainThread) [custom_components.google_home] 
2024-03-24 20:59:15.030 DEBUG (SyncWorker_55) [homeassistant.util.yaml.loader] Secret google_keep_username retrieved from secrets.yaml in folder /config

2024-03-24 20:59:15.032 DEBUG (SyncWorker_55) [homeassistant.util.yaml.loader] Secret google_keep_password retrieved from secrets.yaml in folder /config
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
    login_success = keep.login(username, password)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
					
2024-03-24 21:00:18.531 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_assistant_sdk_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant


```

**Comment by KapJI** [comment]
Exception `unconverted data remains` is from `google_keep` custom extension.

Please check alternative approaches for fetching master token: https://github.com/leikoilja/ha-google-home#master-token

**Comment by IIIdefconIII** [comment]
> Exception `unconverted data remains` is from `google_keep` custom extension.
> 
> Please check alternative approaches for fetching master token: https://github.com/leikoilja/ha-google-home#master-token

ill probably just remove the google keep because i was never able to get it workin, thanks so much to point me into the right direction and continue my path tomorrow!, really appriciate your quick reponse!

**Comment by IIIdefconIII** [comment]
> Exception `unconverted data remains` is from `google_keep` custom extension.
> 
> Please check alternative approaches for fetching master token: https://github.com/leikoilja/ha-google-home#master-token

if i may ask, should i run this pip install glocaltokens command in the cli in a vm of homeassistant?

**Comment by IIIdefconIII** [comment]
> Exception `unconverted data remains` is from `google_keep` custom extension.
> 
> Please check alternative approaches for fetching master token: https://github.com/leikoilja/ha-google-home#master-token

Think i fall in love with ur brains and support ! thanks mate! im  a step closer know, later today ill figure out what to do next;

![image](https://github.com/leikoilja/ha-google-home/assets/9917659/bcf64e3f-628b-493b-9679-80d137d63c33)

**Comment by IIIdefconIII** [comment]
> Exception `unconverted data remains` is from `google_keep` custom extension.
> 
> Please check alternative approaches for fetching master token: https://github.com/leikoilja/ha-google-home#master-token

if i may ask shouldnt i see entities coming from google? i even have nabu casa

**Comment by IIIdefconIII** [comment]
still  nothing...

**Comment by IIIdefconIII** [comment]
why is this ticket closed without any further follow up?! im still fighting this...

**Comment by leikoilja** [comment]
@IIIdefconIII, the initial issue that you open was related to `google_keep` and has been resolved. 
if you encounter issues with not being able to see any devices now that you successfully installed `ha-google-home` integration, please open a new issue, follow TROUBLESHOOTING guide from README and post the issue according to the description providing useful logs :)

**Comment by IIIdefconIII** [comment]
> @IIIdefconIII, the initial issue that you open was related to `google_keep` and has been resolved. if you encounter issues with not being able to see any devices now that you successfully installed `ha-google-home` integration, please open a new issue, follow TROUBLESHOOTING guide from README and post the issue according to the description providing useful logs :)

hi @leikoilja i hope i find the time to check this out again this week. i have the google keep up to date but not working here
