### ISSUE TITLE
Enable strict typing

### ISSUE THREAD

**Issue by KapJI** [leikoilja/ha-google-home#85]
# Problem
Having types and type checks helps to:
- Check that all functions exist and called with correct arguments.
- Make the code more robust.
- Allow to refactor code simpler and safer.
# The plan
I'll enable `mypy` checks soon and will gradually enable stricter checks as more parts are covered with types.

Let me know what do you think!

**Comment by leikoilja** [comment]
I think that would be a great additive! I have already set up my `vim` to support `mypy`, though haven't really adapted to using it just yet! 😄  But i think it would be great adding it

**Comment by KapJI** [comment]
First step: #88

**Comment by KapJI** [comment]
Opened a PR in homeassistant core: https://github.com/home-assistant/core/pull/47796

**Comment by leikoilja** [comment]
Did they close home-assistant/core#47796 because they don't support typing across the entire `core` repo? 🤔  😞

**Comment by KapJI** [comment]
Yeah, basically they have many untyped components (the actual core is strictly typed) and they fear enabling this can break typing of custom components (only those which import *untyped* standard components, popular ones like `sensor` or `light` are typed) therefore it's better to not mark their package as typed.

I don't agree with this but I actually have a workaround. I can generate typing stubs and publish them as a separate package which developer or custom components can install have type check their code against `homeassistant` package.

**Comment by leikoilja** [comment]
uuu, that would be interesting to see :) 
So why is all that hassle? To be able to use typing hints, right? :D

**Comment by KapJI** [comment]
Well, I think this should be useful. Not just for this project but other custom components as well.

**Comment by leikoilja** [comment]
ou no no, i totally think it would be useful what you are proposing with making a stub as a separate package. 

I just mean the entire `mypy` is used for typing help, right? (as u probs already understood, that's quite a new concept for me at this point)

**Comment by KapJI** [comment]
Yes, `mypy` is used for type checking. Without it (or another type checker like `pyre`) type hints are useless 🙂

**Comment by KapJI** [comment]
As I mentioned in the description, having type hints helps to make sure you're passing arguments with the correct types and this helps to avoid mistakes.

**Comment by leikoilja** [comment]
@KapJI, is there anything left from `typing` to implement?

**Comment by KapJI** [comment]
Yes, few things.

1. Add `homeassistant-stubs`. I already created [the package](https://pypi.org/project/homeassistant-stubs/). Waiting for the release of homeassistant 2021.4.0 next Wednesday. I can probably start using beta version in the meantime.
2. Annotate `config_flow`. This depends on 1.

**Comment by leikoilja** [comment]
Oh that's a really nice job! You went far with it 💥
