### ISSUE TITLE
Cant get master token

### ISSUE THREAD

**Issue by crankygamer** [leikoilja/ha-google-home#867]
## Describe the bug

Logger: glocaltokens.client
Bron: custom_components/google_home/api.py:74
integratie: google_home ([documentatie](https://github.com/leikoilja/ha-google-home), [problemen](https://github.com/leikoilja/ha-google-home/issues))
Eerst voorgekomen: 10:42:11 (1 gebeurtenissen)
Laatst gelogd: 10:42:11
[!] Could not get master token.

## Version of the integration

Latest

## Logs

Logger: glocaltokens.client
Bron: custom_components/google_home/api.py:74
integratie: google_home ([documentatie](https://github.com/leikoilja/ha-google-home), [problemen](https://github.com/leikoilja/ha-google-home/issues))
Eerst voorgekomen: 10:42:11 (1 gebeurtenissen)
Laatst gelogd: 10:42:11
[!] Could not get master token.

**Comment by leikoilja** [comment]
please use search as this is a frequent issue and depends on many different things.
https://github.com/search?q=repo%3Aleikoilja%2Fha-google-home+cant+get+master+token&type=issues
