### ISSUE TITLE
Cannot retrieve Master token. Master token returns value "None"

### ISSUE THREAD

**Issue by XalaTheShepard** [leikoilja/ha-google-home#878]
Dear Leikoilja, 

I am using your integration for years. 
A few days ago I have noticed I get error messages. 
To solve this issue I have deleted the integration and tried to add it again. 
However, it now asks me for a master token. 

With the Python method I only get the master token "None". 
For some reason I can not use the docker method, as it does not allow me to complete the information. 

Could you please point me in the right direction? 

Many thanks. 

Kind regards, 

Robin

**Comment by JOrion9999** [comment]
I hope you have a backup .. this is in issue with the latest update (Home Assistant 2024.6.1)  https://github.com/leikoilja/ha-google-home/issues/876. Its been noted that going back to 2024.6.0 resolves the issue. Not sure if the python method for master token is related to this but I too had the same issue. I deleted the integration  and tried to install it again, ran the python script and got the  "none" result. 

I ended up restoring a backup that was made at 1 am today lol .. so its back and still failing but I'm assuming that someone will come up with a fix There will be an update eventually. It should start working again .. but if not I do have a backup to 2024.6.0 that i can restore   

Good luck .. I hope you can restore a backup and get Google Home back .. even if it isn't working at the moment

**Comment by JOrion9999** [comment]
sorry about that ... well there was a hacs update and now Google Home works again. Don't know if the script works now to allow you to get the token needed to reinstall Google Home. I think that is a different thing and I didn't see a fix for that one yet.. and I didn't see a way to restore Google home separately .. i had to just do a full restore to get it back and then I saw the update in hacs and as I say .. its now working again
