### ISSUE TITLE
App password login will not work

### ISSUE THREAD

**Issue by rugene76** [leikoilja/ha-google-home#880]
## Describe the bug

       Google Home will no longer sign into google. Its been working fine for a long time, but now, it stopped authenticating, After I generate a new app password the authentication fails using the new app password and my user login for google

## Version of the integration - latest available on HA, 1.11.1

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
Add version here.
```

## Logs

```text
Add your logs here.
```

**Comment by rugene76** [comment]
that entry form is a mess....
here's the error on the login page:
Username/Password is incorrect. If your google account has 2FA enabled please generate app password

**Comment by rugene76** [comment]
don't close this issue - I have already done all the suggested trouble shooting tips - why would you assume otherwise?

I still have the issue and it needs investigation.

**Comment by leikoilja** [comment]
> don't close this issue - I have already done all the suggested trouble shooting tips - why would you assume otherwise?
> 
> I still have the issue and it needs investigation.

have you tried using `master_token` instead of login and pass?

**Comment by rugene76** [comment]
no, its too involved for the pay back. The app password should work and has for me for some time until now.

I'll guess I'll give up....

**Comment by dark-swordsman** [comment]
I also have having a similar issue. It's a bit silly to go through the effort of trying to setup an app password if we need to do another entire step that involves booting a random docker container that has questionable lineage or reliability just to get another token to access the google account.
