### ISSUE TITLE
[!] Could not get access token.

### ISSUE THREAD

**Issue by DanielvG-IT** [leikoilja/ha-google-home#884]
## Describe the bug

If i fill in my account details and press on "send" then i get the error:
"Username/Password is incorrect. If your Google Account has 2FA enabled, generate an app password (https://myaccount.google.com/apppasswords). If authentication still fails, please refer to https://github.com/leikoilja/ha-google-home#troubleshooting"

I tried logging in with both my application password an my real password. They both didn't work. I have 2fa enabled but when I used my real credentials, it took way longer for the error to show up (THE FIRST TIME!).

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
v1.11.1
```
## Logs

```text
Logger: glocaltokens.client
Source: custom_components/google_home/api.py:75
integration: google_home (documentation, issues)
First occurred: 14:26:33 (5 events)
Last logged: 14:31:08

[!] Could not get master token.


Logger: custom_components.google_home
Source: custom_components/google_home/config_flow.py:132
integration: google_home (documentation, issues)
First occurred: 14:26:33 (5 events)
Last logged: 14:31:08
```

**Comment by leikoilja** [comment]
Please use troubleshooting guide from README to get and use `master` token instead:
https://github.com/leikoilja/ha-google-home#master-token

**Comment by DanielvG-IT** [comment]
I have tried it via a docker container on a Ubuntu VM but it still fails!

![image](https://github.com/user-attachments/assets/ca1514e8-46a4-466a-a122-16528c79db5b)
