### ISSUE TITLE
Input a valid master token but it said it doesn't follow the AAS_ET format.

### ISSUE THREAD

**Issue by e1018e1018** [leikoilja/ha-google-home#889]
## Describe the bug

I have generated an app password and successfully created the master token using [this Docker](https://hub.docker.com/r/breph/ha-google-home_get-token). However, when setting it up for the first time, it says `Master token invalid. Make sure that the full token has been specified (including 'aas_et/')`. I am certain that the master token is in the correct format, like `aas_et/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=` without any spaces.

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.11.1
```

## Logs

```text
2024-07-11 16:59:00.688 ERROR (MainThread) [glocaltokens.client] master_token doesn't follow the AAS_ET format
2024-07-11 16:59:00.790 ERROR (SyncWorker_8) [glocaltokens.client] [!] Could not get access token.
2024-07-11 16:59:00.796 ERROR (MainThread) [custom_components.google_home] 
```

**Comment by leikoilja** [comment]
seems to be the same issue as reported in: https://github.com/leikoilja/ha-google-home/issues/812
@e1018e1018, i ll close this issue in favour of the other one. @e1018e1018 would you be interested in contributing to help fix it by relaxing the check for the master token a bit as described in the other ticket?

**Comment by e1018e1018** [comment]
I found that it says Token must be exactly 223 characters long in #812 , which is not the same as my token. 
Finally, I discovered that the token I copied had an EOL (end-of-line) character. After removing it, I successfully logged in. 
Thanks for your help 😄
