### ISSUE TITLE
Support for nest doorbell that's been transferred to Google home

### ISSUE THREAD

**Issue by Shaun-Harrison** [leikoilja/ha-google-home#898]
I've been able to transfer my nest doorbell to the Google home app. The camera shows as offline in nest now so the previous Google nest integration no longer works on home assistant. 

So far the doorbell hasn't showed up in the Google home integration, so wondering if there will be support for this?

**Comment by leikoilja** [comment]
@Shaun-Harrison i would not expect it to appear in this integration at this time. This integration mostly deals with alarm/timer/dnd management for google home enabled devices, not managing all other google home smart devices
