### ISSUE TITLE
Issue with token local_auth_token

### ISSUE THREAD

**Issue by philippefs35** [leikoilja/ha-google-home#91]
## Version of the custom_component

- ha-google-home v1.0.0
- core-2021.3.3
- supervisor-2021.03.4

## Configuration

Installed through HACS

Created app password since I use 2FA

## Describe the bug

No error during initial configuration (when I enter my Google account and app password), but I don't see any sensors. Seems like it's trying again and again to connect (without success). My Google account on other devices has been signing out due to the repeated attempts...

## Debug log

```text

2021-03-12 17:44:22 ERROR (SyncWorker_1) [glocaltokens.client] local_auth_token doesn't follow the correct format.
2021-03-12 17:44:22 ERROR (MainThread) [custom_components.google_home] Unexpected error fetching sensor data: 'Device' object has no attribute 'ip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 139, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/google_home/api.py", line 164, in update_google_devices_information
    devices = await self.get_google_devices()
  File "/config/custom_components/google_home/api.py", line 74, in get_google_devices
    self.google_devices = [
  File "/config/custom_components/google_home/api.py", line 78, in <listcomp>
    ip_address=device.ip,
AttributeError: 'Device' object has no attribute 'ip'

```

**Comment by leikoilja** [comment]
Thanks for reporting it, @philippefs35. 
Sorry it has logged out all of your google devices, but that's the security behind Google 😄 
What i can see here are two problems:
1. In the underlying `glocaltokens` package this integration is using we do a validation of a `local authentication token`, however, if the validation fails (as it has happened in your case) we still initialize and return the object. We should not be doing that, instead if the validation fails we should just skip adding this device. I have created a corresponding issue [here](https://github.com/leikoilja/glocaltokens/issues/44) that will have to be taken care of to avoid propagated errors as you are having.
2. Somehow the `local authentication token` that you have received from Google is invalid. This is my first time seeing this, so i am a bit surprised and curious what kind of data are you actually receiving there. If you are interested in helping our you can try obtaining those tokens in isolation away from this integration. You can do that by trying [glocaltokens](https://github.com/leikoilja/glocaltokens) python package(this integration uses glocaltokens under the hood) on your laptop/pc. It will allow you to make sure your username/password are right and the package returns all data as expected (see `example/get_tokens.py`) and if the error that you are getting persist you will see the python package failing with the same error message "local_auth_token doesn't follow the correct format.". 
If that happens please try this sketch:
```python
    client = GLocalAuthenticationTokens(
        username=GOOGLE_USERNAME,
        password=GOOGLE_PASSWORD,
        master_token=GOOGLE_MASTER_TOKEN,
        android_id=DEVICE_ID,
    )
    homegraph = client.get_homegraph()
    for item in homegraph.home.devices:
        if item.local_auth_token != "":
            print(item.local_auth_token)
```
This will print all of your local authentication tokens from all the devices connected to your google account. They are changed about every day, but are still somewhat sensitive data(you might want to change a few symbols here and there). If you will get to this point - paste them [to corresponding bug issue](https://github.com/leikoilja/glocaltokens/issues/44), so we can improve validation and checks.

**Comment by leikoilja** [comment]
We have now merged the fix(see [here](https://github.com/leikoilja/glocaltokens/pull/45#event-4457809346)) for the bug you were having, so after a new release of `glocaltokens` comes out it will not recognize non google home devices that have a token of a different format than expected. :)  So I'll close the issue
