### ISSUE TITLE
Update to v1.12.0 fails

### ISSUE THREAD

**Issue by gpion** [leikoilja/ha-google-home#927]
Hello,

I'm currently running HA version 2024.11.2
Updating to v1.12.0 fails with the following error:
_"Failed to perform the action update/install. This version requires Home Assistant 2024.11.0b0 or newer."_

**Comment by KapJI** [comment]
You can't be running 2024.11.2 as it's not released yet. https://github.com/home-assistant/core/releases

**Comment by gpion** [comment]
You're right, I'm running HA CORE version 2024.10.4
Looks loke I  just have to wait 2024.11.* version show up as an available updates

**Comment by gpion** [comment]
You're right, I'm running HA CORE version 2024.10.4
I guess I just have to wait 2024.11.* version show up in the available update

**Comment by KapJI** [comment]
It won't take long, 2024.11.0 should be released in the next few days.
