### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ViPeR5000** [leikoilja/ha-google-home#928]
Falha ao executar a ação update/install. This version requires Home Assistant 2024.11.0b0 or newer.

![Screenshot_20241106-203437](https://github.com/user-attachments/assets/fb694606-bcbb-464a-bfb8-c2a4b3149ecf)

**Comment by KapJI** [comment]
Please post in English. You need to wait before HA 2024.11 is released.

**Comment by ViPeR5000** [comment]
Sorry Yes i need to wait :)
