### ISSUE TITLE
HACS Documentation

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/ha-google-home#98]
Super happy to announce that the integration has aired in the default HACS [repo](https://github.com/hacs/default/pull/859#event-4486751242), so one should not need to add custom repo anymore 💥 

We would need to update the `README` documentation about installation and try it ourselves :)

**Comment by DurgNomis-drol** [comment]
I just tested it and it works. 🚀 🎉 

Will change the snippet in the readme to just search for it in HACS instead of adding it as a custom repository. 😄
